# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rn_admin_validation_summary.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_validationSummaryDialog(object):
    def setupUi(self, validationSummaryDialog):
        validationSummaryDialog.setObjectName("validationSummaryDialog")
        validationSummaryDialog.resize(1051, 810)
        validationSummaryDialog.setMinimumSize(QtCore.QSize(1051, 810))
        self.gridLayout_7 = QtWidgets.QGridLayout(validationSummaryDialog)
        self.gridLayout_7.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_7.setSpacing(6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.tabWidget = QtWidgets.QTabWidget(validationSummaryDialog)
        self.tabWidget.setObjectName("tabWidget")
        self.streetOptTab = QtWidgets.QWidget()
        self.streetOptTab.setObjectName("streetOptTab")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.streetOptTab)
        self.gridLayout_25.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_25.setSpacing(6)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.groupBox = QtWidgets.QGroupBox(self.streetOptTab)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_24.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_24.setSpacing(6)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.dupDesTable = QtWidgets.QTableWidget(self.groupBox)
        self.dupDesTable.setMinimumSize(QtCore.QSize(494, 180))
        self.dupDesTable.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.dupDesTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.dupDesTable.setAutoScroll(True)
        self.dupDesTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.dupDesTable.setAlternatingRowColors(True)
        self.dupDesTable.setSelectionMode(QtWidgets.QAbstractItemView.ContiguousSelection)
        self.dupDesTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.dupDesTable.setObjectName("dupDesTable")
        self.dupDesTable.setColumnCount(0)
        self.dupDesTable.setRowCount(0)
        self.gridLayout_24.addWidget(self.dupDesTable, 0, 0, 1, 1)
        self.gridLayout_25.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.streetOptTab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_23.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_23.setSpacing(6)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.noLinkEsuTable = QtWidgets.QTableWidget(self.groupBox_2)
        self.noLinkEsuTable.setMinimumSize(QtCore.QSize(462, 180))
        self.noLinkEsuTable.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.noLinkEsuTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.noLinkEsuTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.noLinkEsuTable.setAlternatingRowColors(True)
        self.noLinkEsuTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.noLinkEsuTable.setObjectName("noLinkEsuTable")
        self.noLinkEsuTable.setColumnCount(0)
        self.noLinkEsuTable.setRowCount(0)
        self.gridLayout_23.addWidget(self.noLinkEsuTable, 0, 0, 1, 1)
        self.gridLayout_25.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.type3GroupBox = QtWidgets.QGroupBox(self.streetOptTab)
        self.type3GroupBox.setObjectName("type3GroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.type3GroupBox)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.noType3Table = QtWidgets.QTableWidget(self.type3GroupBox)
        self.noType3Table.setMinimumSize(QtCore.QSize(332, 180))
        self.noType3Table.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.noType3Table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.noType3Table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.noType3Table.setAlternatingRowColors(True)
        self.noType3Table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.noType3Table.setObjectName("noType3Table")
        self.noType3Table.setColumnCount(0)
        self.noType3Table.setRowCount(0)
        self.gridLayout.addWidget(self.noType3Table, 0, 0, 1, 1)
        self.noType3Label = QtWidgets.QLabel(self.type3GroupBox)
        self.noType3Label.setText("")
        self.noType3Label.setObjectName("noType3Label")
        self.gridLayout.addWidget(self.noType3Label, 1, 0, 1, 1)
        self.gridLayout_25.addWidget(self.type3GroupBox, 2, 0, 1, 1)
        self.tabWidget.addTab(self.streetOptTab, "")
        self.esuOptTab = QtWidgets.QWidget()
        self.esuOptTab.setObjectName("esuOptTab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.esuOptTab)
        self.gridLayout_5.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.dupEsuRefGroupBox = QtWidgets.QGroupBox(self.esuOptTab)
        self.dupEsuRefGroupBox.setObjectName("dupEsuRefGroupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.dupEsuRefGroupBox)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.dupEsuRefTable = QtWidgets.QTableWidget(self.dupEsuRefGroupBox)
        self.dupEsuRefTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.dupEsuRefTable.setAlternatingRowColors(True)
        self.dupEsuRefTable.setSelectionMode(QtWidgets.QAbstractItemView.ContiguousSelection)
        self.dupEsuRefTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.dupEsuRefTable.setObjectName("dupEsuRefTable")
        self.dupEsuRefTable.setColumnCount(0)
        self.dupEsuRefTable.setRowCount(0)
        self.gridLayout_3.addWidget(self.dupEsuRefTable, 0, 0, 1, 1)
        self.dupEsuRefLabel = QtWidgets.QLabel(self.dupEsuRefGroupBox)
        self.dupEsuRefLabel.setText("")
        self.dupEsuRefLabel.setObjectName("dupEsuRefLabel")
        self.gridLayout_3.addWidget(self.dupEsuRefLabel, 1, 0, 1, 1)
        self.horizontalLayout_5.addWidget(self.dupEsuRefGroupBox)
        self.notEsuStreetGroupBox = QtWidgets.QGroupBox(self.esuOptTab)
        self.notEsuStreetGroupBox.setObjectName("notEsuStreetGroupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.notEsuStreetGroupBox)
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.notEsuStreetTable = QtWidgets.QTableWidget(self.notEsuStreetGroupBox)
        self.notEsuStreetTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.notEsuStreetTable.setAlternatingRowColors(True)
        self.notEsuStreetTable.setSelectionMode(QtWidgets.QAbstractItemView.ContiguousSelection)
        self.notEsuStreetTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.notEsuStreetTable.setObjectName("notEsuStreetTable")
        self.notEsuStreetTable.setColumnCount(0)
        self.notEsuStreetTable.setRowCount(0)
        self.gridLayout_4.addWidget(self.notEsuStreetTable, 0, 0, 1, 1)
        self.horizontalLayout_5.addWidget(self.notEsuStreetGroupBox)
        self.gridLayout_5.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.invCrossRefGroupBox = QtWidgets.QGroupBox(self.esuOptTab)
        self.invCrossRefGroupBox.setObjectName("invCrossRefGroupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.invCrossRefGroupBox)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setContentsMargins(0, 11, 11, 11)
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.type12StreetsTable = QtWidgets.QTableWidget(self.invCrossRefGroupBox)
        self.type12StreetsTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.type12StreetsTable.setAlternatingRowColors(True)
        self.type12StreetsTable.setSelectionMode(QtWidgets.QAbstractItemView.ContiguousSelection)
        self.type12StreetsTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.type12StreetsTable.setObjectName("type12StreetsTable")
        self.type12StreetsTable.setColumnCount(0)
        self.type12StreetsTable.setRowCount(0)
        self.verticalLayout_8.addWidget(self.type12StreetsTable)
        self.label = QtWidgets.QLabel(self.invCrossRefGroupBox)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout_8.addWidget(self.label)
        self.horizontalLayout_4.addLayout(self.verticalLayout_8)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(0, 11, 11, 11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.type34StreetsTable = QtWidgets.QTableWidget(self.invCrossRefGroupBox)
        self.type34StreetsTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.type34StreetsTable.setAlternatingRowColors(True)
        self.type34StreetsTable.setSelectionMode(QtWidgets.QAbstractItemView.ContiguousSelection)
        self.type34StreetsTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.type34StreetsTable.setObjectName("type34StreetsTable")
        self.type34StreetsTable.setColumnCount(0)
        self.type34StreetsTable.setRowCount(0)
        self.verticalLayout_5.addWidget(self.type34StreetsTable)
        self.label_2 = QtWidgets.QLabel(self.invCrossRefGroupBox)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(0, 11, 11, 11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.unofficialTypeStreetsTable = QtWidgets.QTableWidget(self.invCrossRefGroupBox)
        self.unofficialTypeStreetsTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.unofficialTypeStreetsTable.setAlternatingRowColors(True)
        self.unofficialTypeStreetsTable.setSelectionMode(QtWidgets.QAbstractItemView.ContiguousSelection)
        self.unofficialTypeStreetsTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.unofficialTypeStreetsTable.setObjectName("unofficialTypeStreetsTable")
        self.unofficialTypeStreetsTable.setColumnCount(0)
        self.unofficialTypeStreetsTable.setRowCount(0)
        self.verticalLayout_4.addWidget(self.unofficialTypeStreetsTable)
        self.label_3 = QtWidgets.QLabel(self.invCrossRefGroupBox)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.invCrossRefGroupBox, 1, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.startEndGroupBox = QtWidgets.QGroupBox(self.esuOptTab)
        self.startEndGroupBox.setObjectName("startEndGroupBox")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.startEndGroupBox)
        self.gridLayout_6.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_6.setSpacing(6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.startEndTable = QtWidgets.QTableWidget(self.startEndGroupBox)
        self.startEndTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.startEndTable.setAlternatingRowColors(True)
        self.startEndTable.setSelectionMode(QtWidgets.QAbstractItemView.ContiguousSelection)
        self.startEndTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.startEndTable.setObjectName("startEndTable")
        self.startEndTable.setColumnCount(0)
        self.startEndTable.setRowCount(0)
        self.gridLayout_6.addWidget(self.startEndTable, 0, 0, 1, 1)
        self.toleranceLabel = QtWidgets.QLabel(self.startEndGroupBox)
        self.toleranceLabel.setMinimumSize(QtCore.QSize(0, 30))
        self.toleranceLabel.setMaximumSize(QtCore.QSize(225, 30))
        self.toleranceLabel.setWordWrap(True)
        self.toleranceLabel.setObjectName("toleranceLabel")
        self.gridLayout_6.addWidget(self.toleranceLabel, 1, 0, 1, 1)
        self.horizontalLayout_6.addWidget(self.startEndGroupBox)
        self.tinyEsuGroupBox = QtWidgets.QGroupBox(self.esuOptTab)
        self.tinyEsuGroupBox.setObjectName("tinyEsuGroupBox")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.tinyEsuGroupBox)
        self.gridLayout_10.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_10.setSpacing(6)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.tinyEsuTable = QtWidgets.QTableWidget(self.tinyEsuGroupBox)
        self.tinyEsuTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tinyEsuTable.setAlternatingRowColors(True)
        self.tinyEsuTable.setSelectionMode(QtWidgets.QAbstractItemView.ContiguousSelection)
        self.tinyEsuTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tinyEsuTable.setObjectName("tinyEsuTable")
        self.tinyEsuTable.setColumnCount(0)
        self.tinyEsuTable.setRowCount(0)
        self.gridLayout_10.addWidget(self.tinyEsuTable, 0, 0, 1, 1)
        self.horizontalLayout_6.addWidget(self.tinyEsuGroupBox)
        self.noGeomEsuGroupBox = QtWidgets.QGroupBox(self.esuOptTab)
        self.noGeomEsuGroupBox.setObjectName("noGeomEsuGroupBox")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.noGeomEsuGroupBox)
        self.gridLayout_11.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_11.setSpacing(6)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.noGeomEsuTable = QtWidgets.QTableWidget(self.noGeomEsuGroupBox)
        self.noGeomEsuTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.noGeomEsuTable.setAlternatingRowColors(True)
        self.noGeomEsuTable.setSelectionMode(QtWidgets.QAbstractItemView.ContiguousSelection)
        self.noGeomEsuTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.noGeomEsuTable.setObjectName("noGeomEsuTable")
        self.noGeomEsuTable.setColumnCount(0)
        self.noGeomEsuTable.setRowCount(0)
        self.gridLayout_11.addWidget(self.noGeomEsuTable, 0, 0, 1, 1)
        self.horizontalLayout_6.addWidget(self.noGeomEsuGroupBox)
        self.gridLayout_5.addLayout(self.horizontalLayout_6, 2, 0, 1, 1)
        self.tabWidget.addTab(self.esuOptTab, "")
        self.asdOptTab = QtWidgets.QWidget()
        self.asdOptTab.setObjectName("asdOptTab")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.asdOptTab)
        self.gridLayout_15.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_15.setSpacing(6)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.notMaintGroupBox = QtWidgets.QGroupBox(self.asdOptTab)
        self.notMaintGroupBox.setObjectName("notMaintGroupBox")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.notMaintGroupBox)
        self.gridLayout_8.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_8.setSpacing(6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.notMaintTable = QtWidgets.QTableWidget(self.notMaintGroupBox)
        self.notMaintTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.notMaintTable.setAlternatingRowColors(True)
        self.notMaintTable.setSelectionMode(QtWidgets.QAbstractItemView.ContiguousSelection)
        self.notMaintTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.notMaintTable.setObjectName("notMaintTable")
        self.notMaintTable.setColumnCount(0)
        self.notMaintTable.setRowCount(0)
        self.gridLayout_8.addWidget(self.notMaintTable, 0, 0, 1, 1)
        self.horizontalLayout_7.addWidget(self.notMaintGroupBox)
        self.notReinsGroupBox = QtWidgets.QGroupBox(self.asdOptTab)
        self.notReinsGroupBox.setObjectName("notReinsGroupBox")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.notReinsGroupBox)
        self.gridLayout_9.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_9.setSpacing(6)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.notReinsTable = QtWidgets.QTableWidget(self.notReinsGroupBox)
        self.notReinsTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.notReinsTable.setAlternatingRowColors(True)
        self.notReinsTable.setSelectionMode(QtWidgets.QAbstractItemView.ContiguousSelection)
        self.notReinsTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.notReinsTable.setObjectName("notReinsTable")
        self.notReinsTable.setColumnCount(0)
        self.notReinsTable.setRowCount(0)
        self.gridLayout_9.addWidget(self.notReinsTable, 0, 0, 1, 1)
        self.horizontalLayout_7.addWidget(self.notReinsGroupBox)
        self.gridLayout_15.addLayout(self.horizontalLayout_7, 0, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.asdMaintCoordGroupBox = QtWidgets.QGroupBox(self.asdOptTab)
        self.asdMaintCoordGroupBox.setObjectName("asdMaintCoordGroupBox")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.asdMaintCoordGroupBox)
        self.gridLayout_12.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_12.setSpacing(6)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.asdMaintCoordTable = QtWidgets.QTableWidget(self.asdMaintCoordGroupBox)
        self.asdMaintCoordTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.asdMaintCoordTable.setAlternatingRowColors(True)
        self.asdMaintCoordTable.setSelectionMode(QtWidgets.QAbstractItemView.ContiguousSelection)
        self.asdMaintCoordTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.asdMaintCoordTable.setObjectName("asdMaintCoordTable")
        self.asdMaintCoordTable.setColumnCount(0)
        self.asdMaintCoordTable.setRowCount(0)
        self.gridLayout_12.addWidget(self.asdMaintCoordTable, 0, 0, 1, 1)
        self.horizontalLayout_8.addWidget(self.asdMaintCoordGroupBox)
        self.asdSpecDesCoordGroupBox = QtWidgets.QGroupBox(self.asdOptTab)
        self.asdSpecDesCoordGroupBox.setObjectName("asdSpecDesCoordGroupBox")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.asdSpecDesCoordGroupBox)
        self.gridLayout_13.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_13.setSpacing(6)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.asdSpecDesCoordTable = QtWidgets.QTableWidget(self.asdSpecDesCoordGroupBox)
        self.asdSpecDesCoordTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.asdSpecDesCoordTable.setAlternatingRowColors(True)
        self.asdSpecDesCoordTable.setSelectionMode(QtWidgets.QAbstractItemView.ContiguousSelection)
        self.asdSpecDesCoordTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.asdSpecDesCoordTable.setObjectName("asdSpecDesCoordTable")
        self.asdSpecDesCoordTable.setColumnCount(0)
        self.asdSpecDesCoordTable.setRowCount(0)
        self.gridLayout_13.addWidget(self.asdSpecDesCoordTable, 0, 0, 1, 1)
        self.horizontalLayout_8.addWidget(self.asdSpecDesCoordGroupBox)
        self.asdReinsCoordGroupBox = QtWidgets.QGroupBox(self.asdOptTab)
        self.asdReinsCoordGroupBox.setObjectName("asdReinsCoordGroupBox")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.asdReinsCoordGroupBox)
        self.gridLayout_14.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_14.setSpacing(6)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.asdReinsCoordTable = QtWidgets.QTableWidget(self.asdReinsCoordGroupBox)
        self.asdReinsCoordTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.asdReinsCoordTable.setAlternatingRowColors(True)
        self.asdReinsCoordTable.setSelectionMode(QtWidgets.QAbstractItemView.ContiguousSelection)
        self.asdReinsCoordTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.asdReinsCoordTable.setObjectName("asdReinsCoordTable")
        self.asdReinsCoordTable.setColumnCount(0)
        self.asdReinsCoordTable.setRowCount(0)
        self.gridLayout_14.addWidget(self.asdReinsCoordTable, 0, 0, 1, 1)
        self.horizontalLayout_8.addWidget(self.asdReinsCoordGroupBox)
        self.gridLayout_15.addLayout(self.horizontalLayout_8, 1, 0, 1, 1)
        self.tabWidget.addTab(self.asdOptTab, "")
        self.polyOptTab = QtWidgets.QWidget()
        self.polyOptTab.setObjectName("polyOptTab")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.polyOptTab)
        self.gridLayout_22.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_22.setSpacing(6)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.gridLayout_21 = QtWidgets.QGridLayout()
        self.gridLayout_21.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_21.setSpacing(6)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.maintRecGroupBox = QtWidgets.QGroupBox(self.polyOptTab)
        self.maintRecGroupBox.setObjectName("maintRecGroupBox")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.maintRecGroupBox)
        self.gridLayout_16.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_16.setSpacing(6)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.maintRecTable = QtWidgets.QTableWidget(self.maintRecGroupBox)
        self.maintRecTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.maintRecTable.setAlternatingRowColors(True)
        self.maintRecTable.setSelectionMode(QtWidgets.QAbstractItemView.ContiguousSelection)
        self.maintRecTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.maintRecTable.setObjectName("maintRecTable")
        self.maintRecTable.setColumnCount(0)
        self.maintRecTable.setRowCount(0)
        self.gridLayout_16.addWidget(self.maintRecTable, 0, 0, 1, 1)
        self.horizontalLayout_9.addWidget(self.maintRecGroupBox)
        self.polyMaintGroupBox = QtWidgets.QGroupBox(self.polyOptTab)
        self.polyMaintGroupBox.setObjectName("polyMaintGroupBox")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.polyMaintGroupBox)
        self.gridLayout_17.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_17.setSpacing(6)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.polyMaintTable = QtWidgets.QTableWidget(self.polyMaintGroupBox)
        self.polyMaintTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.polyMaintTable.setAlternatingRowColors(True)
        self.polyMaintTable.setSelectionMode(QtWidgets.QAbstractItemView.ContiguousSelection)
        self.polyMaintTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.polyMaintTable.setObjectName("polyMaintTable")
        self.polyMaintTable.setColumnCount(0)
        self.polyMaintTable.setRowCount(0)
        self.gridLayout_17.addWidget(self.polyMaintTable, 0, 0, 1, 1)
        self.horizontalLayout_9.addWidget(self.polyMaintGroupBox)
        self.gridLayout_21.addLayout(self.horizontalLayout_9, 0, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_10.setSpacing(6)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.multiPolyGroupBox = QtWidgets.QGroupBox(self.polyOptTab)
        self.multiPolyGroupBox.setObjectName("multiPolyGroupBox")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.multiPolyGroupBox)
        self.gridLayout_18.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_18.setSpacing(6)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.multiPolyTable = QtWidgets.QTableWidget(self.multiPolyGroupBox)
        self.multiPolyTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.multiPolyTable.setAlternatingRowColors(True)
        self.multiPolyTable.setSelectionMode(QtWidgets.QAbstractItemView.ContiguousSelection)
        self.multiPolyTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.multiPolyTable.setObjectName("multiPolyTable")
        self.multiPolyTable.setColumnCount(0)
        self.multiPolyTable.setRowCount(0)
        self.gridLayout_18.addWidget(self.multiPolyTable, 0, 0, 1, 1)
        self.horizontalLayout_10.addWidget(self.multiPolyGroupBox)
        self.tinyPolysGroupBox = QtWidgets.QGroupBox(self.polyOptTab)
        self.tinyPolysGroupBox.setObjectName("tinyPolysGroupBox")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.tinyPolysGroupBox)
        self.gridLayout_19.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_19.setSpacing(6)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.tinyPolysTable = QtWidgets.QTableWidget(self.tinyPolysGroupBox)
        self.tinyPolysTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tinyPolysTable.setAlternatingRowColors(True)
        self.tinyPolysTable.setSelectionMode(QtWidgets.QAbstractItemView.ContiguousSelection)
        self.tinyPolysTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tinyPolysTable.setObjectName("tinyPolysTable")
        self.tinyPolysTable.setColumnCount(0)
        self.tinyPolysTable.setRowCount(0)
        self.gridLayout_19.addWidget(self.tinyPolysTable, 0, 0, 1, 1)
        self.horizontalLayout_10.addWidget(self.tinyPolysGroupBox)
        self.noGeomPolysGroupBox = QtWidgets.QGroupBox(self.polyOptTab)
        self.noGeomPolysGroupBox.setObjectName("noGeomPolysGroupBox")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.noGeomPolysGroupBox)
        self.gridLayout_20.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_20.setSpacing(6)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.noGeomPolysTable = QtWidgets.QTableWidget(self.noGeomPolysGroupBox)
        self.noGeomPolysTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.noGeomPolysTable.setAlternatingRowColors(True)
        self.noGeomPolysTable.setSelectionMode(QtWidgets.QAbstractItemView.ContiguousSelection)
        self.noGeomPolysTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.noGeomPolysTable.setObjectName("noGeomPolysTable")
        self.noGeomPolysTable.setColumnCount(0)
        self.noGeomPolysTable.setRowCount(0)
        self.gridLayout_20.addWidget(self.noGeomPolysTable, 0, 0, 1, 1)
        self.horizontalLayout_10.addWidget(self.noGeomPolysGroupBox)
        self.gridLayout_21.addLayout(self.horizontalLayout_10, 1, 0, 1, 1)
        self.gridLayout_22.addLayout(self.gridLayout_21, 0, 0, 1, 1)
        self.tabWidget.addTab(self.polyOptTab, "")
        self.gridLayout_7.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(validationSummaryDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(validationSummaryDialog)

    def retranslateUi(self, validationSummaryDialog):
        _translate = QtCore.QCoreApplication.translate
        validationSummaryDialog.setWindowTitle(_translate("validationSummaryDialog", "Validation Report Summary"))
        self.groupBox.setTitle(_translate("validationSummaryDialog", "Duplicate street descriptions"))
        self.dupDesTable.setSortingEnabled(False)
        self.groupBox_2.setTitle(_translate("validationSummaryDialog", "Streets not linked to ESU"))
        self.type3GroupBox.setTitle(_translate("validationSummaryDialog", "Streets without Type 3"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.streetOptTab), _translate("validationSummaryDialog", "Street Options"))
        self.dupEsuRefGroupBox.setTitle(_translate("validationSummaryDialog", "Duplicate ESU references"))
        self.dupEsuRefTable.setSortingEnabled(False)
        self.notEsuStreetGroupBox.setTitle(_translate("validationSummaryDialog", "ESUs not linked to street"))
        self.notEsuStreetTable.setSortingEnabled(False)
        self.invCrossRefGroupBox.setTitle(_translate("validationSummaryDialog", "Invalid cross-references"))
        self.type12StreetsTable.setSortingEnabled(False)
        self.label.setText(_translate("validationSummaryDialog", "ESUs incorrectly linked to Type 1 and Type 2 streets"))
        self.type34StreetsTable.setSortingEnabled(False)
        self.label_2.setText(_translate("validationSummaryDialog", "ESUs linked to Type 3 or 4 streets but not to Type 1 or 2"))
        self.unofficialTypeStreetsTable.setSortingEnabled(False)
        self.label_3.setText(_translate("validationSummaryDialog", "ESUs linked to unofficial street types (ie. not 1,2,3or4)"))
        self.startEndGroupBox.setTitle(_translate("validationSummaryDialog", "Start + end coordinates"))
        self.startEndTable.setSortingEnabled(False)
        self.toleranceLabel.setText(_translate("validationSummaryDialog", "Streets with misplaced start/end coordinates. Tolerance: "))
        self.tinyEsuGroupBox.setTitle(_translate("validationSummaryDialog", "Tiny ESUs"))
        self.tinyEsuTable.setSortingEnabled(False)
        self.noGeomEsuGroupBox.setTitle(_translate("validationSummaryDialog", "ESUs with invalid geometry"))
        self.noGeomEsuTable.setSortingEnabled(False)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.esuOptTab), _translate("validationSummaryDialog", "ESU Options"))
        self.notMaintGroupBox.setTitle(_translate("validationSummaryDialog", "Type 1/2 streets not linked to maintenance records"))
        self.notMaintTable.setSortingEnabled(False)
        self.notReinsGroupBox.setTitle(_translate("validationSummaryDialog", "Type 1/2 streets not linked to reinstatement records"))
        self.notReinsTable.setSortingEnabled(False)
        self.asdMaintCoordGroupBox.setTitle(_translate("validationSummaryDialog", "Maintenance records with invalid start-end coordinates"))
        self.asdMaintCoordTable.setSortingEnabled(False)
        self.asdSpecDesCoordGroupBox.setTitle(_translate("validationSummaryDialog", "Special designation records with invalid start-end coordinates"))
        self.asdSpecDesCoordTable.setSortingEnabled(False)
        self.asdReinsCoordGroupBox.setTitle(_translate("validationSummaryDialog", "Reinstatement records with invalid start-end coordinates"))
        self.asdReinsCoordTable.setSortingEnabled(False)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.asdOptTab), _translate("validationSummaryDialog", "ASD Options"))
        self.maintRecGroupBox.setTitle(_translate("validationSummaryDialog", "Maintenance records not linked to any polygons"))
        self.maintRecTable.setSortingEnabled(False)
        self.polyMaintGroupBox.setTitle(_translate("validationSummaryDialog", "Polygons not linked to a maintenance record"))
        self.polyMaintTable.setSortingEnabled(False)
        self.multiPolyGroupBox.setTitle(_translate("validationSummaryDialog", "Polygons wrongly assigned to more than one maintenance record"))
        self.multiPolyTable.setSortingEnabled(False)
        self.tinyPolysGroupBox.setTitle(_translate("validationSummaryDialog", "Tiny polygons"))
        self.tinyPolysTable.setSortingEnabled(False)
        self.noGeomPolysGroupBox.setTitle(_translate("validationSummaryDialog", "Polygons with invalid geometry"))
        self.noGeomPolysTable.setSortingEnabled(False)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.polyOptTab), _translate("validationSummaryDialog", "Polygon Options"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    validationSummaryDialog = QtWidgets.QDialog()
    ui = Ui_validationSummaryDialog()
    ui.setupUi(validationSummaryDialog)
    validationSummaryDialog.show()
    sys.exit(app.exec_())

