# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rn_admin_street_reports_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_streetreports(object):
    def setupUi(self, streetreports):
        streetreports.setObjectName("streetreports")
        streetreports.resize(453, 278)
        self.gridLayout = QtWidgets.QGridLayout(streetreports)
        self.gridLayout.setObjectName("gridLayout")
        self.line = QtWidgets.QFrame(streetreports)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 2, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setContentsMargins(27, 5, 3, 3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tblsRadioButton = QtWidgets.QRadioButton(streetreports)
        self.tblsRadioButton.setObjectName("tblsRadioButton")
        self.gridLayout_3.addWidget(self.tblsRadioButton, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 1, 1, 1)
        self.tblsComboBox = QtWidgets.QComboBox(streetreports)
        self.tblsComboBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblsComboBox.sizePolicy().hasHeightForWidth())
        self.tblsComboBox.setSizePolicy(sizePolicy)
        self.tblsComboBox.setMinimumSize(QtCore.QSize(150, 0))
        self.tblsComboBox.setObjectName("tblsComboBox")
        self.tblsComboBox.addItem("")
        self.tblsComboBox.addItem("")
        self.tblsComboBox.addItem("")
        self.tblsComboBox.addItem("")
        self.gridLayout_3.addWidget(self.tblsComboBox, 0, 2, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 3, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.csvCheckBox = QtWidgets.QCheckBox(streetreports)
        self.csvCheckBox.setObjectName("csvCheckBox")
        self.horizontalLayout_3.addWidget(self.csvCheckBox)
        spacerItem1 = QtWidgets.QSpacerItem(214, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.okPushButton = QtWidgets.QPushButton(streetreports)
        self.okPushButton.setObjectName("okPushButton")
        self.horizontalLayout_3.addWidget(self.okPushButton)
        self.cancelPushButton = QtWidgets.QPushButton(streetreports)
        self.cancelPushButton.setObjectName("cancelPushButton")
        self.horizontalLayout_3.addWidget(self.cancelPushButton)
        self.gridLayout.addLayout(self.horizontalLayout_3, 5, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(27, 5, 3, 3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.changedStsRadioButton = QtWidgets.QRadioButton(streetreports)
        self.changedStsRadioButton.setChecked(True)
        self.changedStsRadioButton.setObjectName("changedStsRadioButton")
        self.gridLayout_2.addWidget(self.changedStsRadioButton, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(streetreports)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 1, 1, 1)
        self.dateEdit = QtWidgets.QDateEdit(streetreports)
        self.dateEdit.setAcceptDrops(False)
        self.dateEdit.setFrame(True)
        self.dateEdit.setAccelerated(False)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout_2.addWidget(self.dateEdit, 0, 2, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fileLabel = QtWidgets.QLabel(streetreports)
        self.fileLabel.setObjectName("fileLabel")
        self.horizontalLayout.addWidget(self.fileLabel)
        self.fileLineEdit = QtWidgets.QLineEdit(streetreports)
        self.fileLineEdit.setObjectName("fileLineEdit")
        self.horizontalLayout.addWidget(self.fileLineEdit)
        self.fileOpenPushButton = QtWidgets.QPushButton(streetreports)
        self.fileOpenPushButton.setText("")
        self.fileOpenPushButton.setObjectName("fileOpenPushButton")
        self.horizontalLayout.addWidget(self.fileOpenPushButton)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.listWidget = QtWidgets.QListWidget(streetreports)
        self.listWidget.setEnabled(False)
        self.listWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.listWidget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.listWidget.setAlternatingRowColors(False)
        self.listWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listWidget.setObjectName("listWidget")
        self.horizontalLayout_2.addWidget(self.listWidget)
        self.gridLayout.addLayout(self.horizontalLayout_2, 4, 0, 1, 1)

        self.retranslateUi(streetreports)
        QtCore.QMetaObject.connectSlotsByName(streetreports)

    def retranslateUi(self, streetreports):
        _translate = QtCore.QCoreApplication.translate
        streetreports.setWindowTitle(_translate("streetreports", "Street Reports"))
        self.tblsRadioButton.setText(_translate("streetreports", "Additional Tables"))
        self.tblsComboBox.setItemText(0, _translate("streetreports", "Select a Table"))
        self.tblsComboBox.setItemText(1, _translate("streetreports", "Maintenance"))
        self.tblsComboBox.setItemText(2, _translate("streetreports", "Reinstatement"))
        self.tblsComboBox.setItemText(3, _translate("streetreports", "Special Designation"))
        self.csvCheckBox.setText(_translate("streetreports", "CSV Formatted"))
        self.okPushButton.setText(_translate("streetreports", "OK"))
        self.cancelPushButton.setText(_translate("streetreports", "Cancel"))
        self.changedStsRadioButton.setText(_translate("streetreports", "Changed Streets"))
        self.label.setText(_translate("streetreports", "Changes Since:"))
        self.fileLabel.setText(_translate("streetreports", "Export To"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    streetreports = QtWidgets.QDialog()
    ui = Ui_streetreports()
    ui.setupUi(streetreports)
    streetreports.show()
    sys.exit(app.exec_())

