# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rn_admin_validation_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_validationDialog(object):
    def setupUi(self, validationDialog):
        validationDialog.setObjectName("validationDialog")
        validationDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        validationDialog.resize(308, 611)
        validationDialog.setModal(True)
        self.gridLayout_3 = QtWidgets.QGridLayout(validationDialog)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.okCancelButtons = QtWidgets.QDialogButtonBox(validationDialog)
        self.okCancelButtons.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.okCancelButtons.setObjectName("okCancelButtons")
        self.gridLayout_3.addWidget(self.okCancelButtons, 7, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.reportLabel = QtWidgets.QLabel(validationDialog)
        self.reportLabel.setObjectName("reportLabel")
        self.horizontalLayout.addWidget(self.reportLabel)
        self.screenRadioButton = QtWidgets.QRadioButton(validationDialog)
        self.screenRadioButton.setObjectName("screenRadioButton")
        self.horizontalLayout.addWidget(self.screenRadioButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.fileRadioButton = QtWidgets.QRadioButton(validationDialog)
        self.fileRadioButton.setObjectName("fileRadioButton")
        self.horizontalLayout.addWidget(self.fileRadioButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout_3.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.filePathLineEdit = QtWidgets.QLineEdit(validationDialog)
        self.filePathLineEdit.setStyleSheet("")
        self.filePathLineEdit.setText("")
        self.filePathLineEdit.setReadOnly(False)
        self.filePathLineEdit.setObjectName("filePathLineEdit")
        self.horizontalLayout_2.addWidget(self.filePathLineEdit)
        self.openPushButton = QtWidgets.QPushButton(validationDialog)
        self.openPushButton.setText("")
        self.openPushButton.setObjectName("openPushButton")
        self.horizontalLayout_2.addWidget(self.openPushButton)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.selectAllButton = QtWidgets.QPushButton(validationDialog)
        self.selectAllButton.setObjectName("selectAllButton")
        self.horizontalLayout_4.addWidget(self.selectAllButton)
        self.clearAllButton = QtWidgets.QPushButton(validationDialog)
        self.clearAllButton.setObjectName("clearAllButton")
        self.horizontalLayout_4.addWidget(self.clearAllButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 6, 0, 1, 1)
        self.esuOptGroupBox = QtWidgets.QGroupBox(validationDialog)
        self.esuOptGroupBox.setObjectName("esuOptGroupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.esuOptGroupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.dupEsuRefCheckBox = QtWidgets.QCheckBox(self.esuOptGroupBox)
        self.dupEsuRefCheckBox.setObjectName("dupEsuRefCheckBox")
        self.gridLayout_4.addWidget(self.dupEsuRefCheckBox, 0, 0, 1, 1)
        self.notEsuStreetCheckBox = QtWidgets.QCheckBox(self.esuOptGroupBox)
        self.notEsuStreetCheckBox.setObjectName("notEsuStreetCheckBox")
        self.gridLayout_4.addWidget(self.notEsuStreetCheckBox, 1, 0, 1, 1)
        self.invCrossRefCheckBox = QtWidgets.QCheckBox(self.esuOptGroupBox)
        self.invCrossRefCheckBox.setObjectName("invCrossRefCheckBox")
        self.gridLayout_4.addWidget(self.invCrossRefCheckBox, 2, 0, 1, 1)
        self.startEndCheckBox = QtWidgets.QCheckBox(self.esuOptGroupBox)
        self.startEndCheckBox.setObjectName("startEndCheckBox")
        self.gridLayout_4.addWidget(self.startEndCheckBox, 3, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.metresSpinBox = QtWidgets.QSpinBox(self.esuOptGroupBox)
        self.metresSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.metresSpinBox.setMaximum(999)
        self.metresSpinBox.setSingleStep(1)
        self.metresSpinBox.setObjectName("metresSpinBox")
        self.horizontalLayout_3.addWidget(self.metresSpinBox)
        self.toleranceLabel = QtWidgets.QLabel(self.esuOptGroupBox)
        self.toleranceLabel.setObjectName("toleranceLabel")
        self.horizontalLayout_3.addWidget(self.toleranceLabel)
        self.gridLayout_4.addLayout(self.horizontalLayout_3, 3, 1, 1, 1)
        self.tinyEsuCheckBox = QtWidgets.QCheckBox(self.esuOptGroupBox)
        self.tinyEsuCheckBox.setObjectName("tinyEsuCheckBox")
        self.gridLayout_4.addWidget(self.tinyEsuCheckBox, 4, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.esuOptGroupBox, 3, 0, 1, 1)
        self.streetOptGroupBox = QtWidgets.QGroupBox(validationDialog)
        self.streetOptGroupBox.setObjectName("streetOptGroupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.streetOptGroupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.dupStreetCheckBox = QtWidgets.QCheckBox(self.streetOptGroupBox)
        self.dupStreetCheckBox.setObjectName("dupStreetCheckBox")
        self.gridLayout.addWidget(self.dupStreetCheckBox, 0, 0, 1, 1)
        self.notStreetEsuCheckBox = QtWidgets.QCheckBox(self.streetOptGroupBox)
        self.notStreetEsuCheckBox.setObjectName("notStreetEsuCheckBox")
        self.gridLayout.addWidget(self.notStreetEsuCheckBox, 1, 0, 1, 1)
        self.notType3CheckBox = QtWidgets.QCheckBox(self.streetOptGroupBox)
        self.notType3CheckBox.setObjectName("notType3CheckBox")
        self.gridLayout.addWidget(self.notType3CheckBox, 2, 0, 1, 1)
        self.incFootPathCheckBox = QtWidgets.QCheckBox(self.streetOptGroupBox)
        self.incFootPathCheckBox.setObjectName("incFootPathCheckBox")
        self.gridLayout.addWidget(self.incFootPathCheckBox, 2, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.streetOptGroupBox, 2, 0, 1, 1)
        self.asdOptGroupBox = QtWidgets.QGroupBox(validationDialog)
        self.asdOptGroupBox.setObjectName("asdOptGroupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.asdOptGroupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.notMaintReinsCheckBox = QtWidgets.QCheckBox(self.asdOptGroupBox)
        self.notMaintReinsCheckBox.setObjectName("notMaintReinsCheckBox")
        self.verticalLayout_2.addWidget(self.notMaintReinsCheckBox)
        self.asdStartEndCheckBox = QtWidgets.QCheckBox(self.asdOptGroupBox)
        self.asdStartEndCheckBox.setObjectName("asdStartEndCheckBox")
        self.verticalLayout_2.addWidget(self.asdStartEndCheckBox)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.gridLayout_3.addWidget(self.asdOptGroupBox, 4, 0, 1, 1)
        self.polyOptGroupBox = QtWidgets.QGroupBox(validationDialog)
        self.polyOptGroupBox.setObjectName("polyOptGroupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.polyOptGroupBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.notMaintPolysCheckBox = QtWidgets.QCheckBox(self.polyOptGroupBox)
        self.notMaintPolysCheckBox.setObjectName("notMaintPolysCheckBox")
        self.verticalLayout_4.addWidget(self.notMaintPolysCheckBox)
        self.notPolysMaintCheckBox = QtWidgets.QCheckBox(self.polyOptGroupBox)
        self.notPolysMaintCheckBox.setObjectName("notPolysMaintCheckBox")
        self.verticalLayout_4.addWidget(self.notPolysMaintCheckBox)
        self.tinyPolysCheckBox = QtWidgets.QCheckBox(self.polyOptGroupBox)
        self.tinyPolysCheckBox.setObjectName("tinyPolysCheckBox")
        self.verticalLayout_4.addWidget(self.tinyPolysCheckBox)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.gridLayout_3.addWidget(self.polyOptGroupBox, 5, 0, 1, 1)
        self.streetOptGroupBox.raise_()
        self.esuOptGroupBox.raise_()
        self.asdOptGroupBox.raise_()
        self.polyOptGroupBox.raise_()
        self.okCancelButtons.raise_()

        self.retranslateUi(validationDialog)
        QtCore.QMetaObject.connectSlotsByName(validationDialog)

    def retranslateUi(self, validationDialog):
        _translate = QtCore.QCoreApplication.translate
        validationDialog.setWindowTitle(_translate("validationDialog", "Quick Find Record"))
        self.reportLabel.setText(_translate("validationDialog", "Report Location:"))
        self.screenRadioButton.setText(_translate("validationDialog", "Screen"))
        self.fileRadioButton.setText(_translate("validationDialog", "File"))
        self.selectAllButton.setText(_translate("validationDialog", "Select All"))
        self.clearAllButton.setText(_translate("validationDialog", "Clear All"))
        self.esuOptGroupBox.setTitle(_translate("validationDialog", "ESU Options"))
        self.dupEsuRefCheckBox.setText(_translate("validationDialog", "Duplicate ESU References"))
        self.notEsuStreetCheckBox.setText(_translate("validationDialog", "ESUs not linked to Street"))
        self.invCrossRefCheckBox.setText(_translate("validationDialog", "Invalid Cross-references"))
        self.startEndCheckBox.setText(_translate("validationDialog", "Start + End Co-ords (slow)"))
        self.toleranceLabel.setText(_translate("validationDialog", "m Tolerance"))
        self.tinyEsuCheckBox.setText(_translate("validationDialog", "Tiny ESUs"))
        self.streetOptGroupBox.setTitle(_translate("validationDialog", "Street Options"))
        self.dupStreetCheckBox.setText(_translate("validationDialog", "Duplicate Street Descriptions"))
        self.notStreetEsuCheckBox.setText(_translate("validationDialog", "Streets not linked to ESU"))
        self.notType3CheckBox.setText(_translate("validationDialog", "Streets without Type 3"))
        self.incFootPathCheckBox.setText(_translate("validationDialog", "(inc. Foothpath)"))
        self.asdOptGroupBox.setTitle(_translate("validationDialog", "ASD Options"))
        self.notMaintReinsCheckBox.setText(_translate("validationDialog", "Streets without Maint / Reinstatement"))
        self.asdStartEndCheckBox.setText(_translate("validationDialog", "ASD Start + End Co-ords"))
        self.polyOptGroupBox.setTitle(_translate("validationDialog", "Polygon Options"))
        self.notMaintPolysCheckBox.setText(_translate("validationDialog", "Maint records not linked to Polys"))
        self.notPolysMaintCheckBox.setText(_translate("validationDialog", "Polys not linked to Maint Records"))
        self.tinyPolysCheckBox.setText(_translate("validationDialog", "Tiny Polys"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    validationDialog = QtWidgets.QDialog()
    ui = Ui_validationDialog()
    ui.setupUi(validationDialog)
    validationDialog.show()
    sys.exit(app.exec_())

