# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rn_admin_srwr_lookup_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_srwrLookupDialog(object):
    def setupUi(self, srwrLookupDialog):
        srwrLookupDialog.setObjectName("srwrLookupDialog")
        srwrLookupDialog.resize(372, 293)
        self.gridLayout_2 = QtWidgets.QGridLayout(srwrLookupDialog)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.typeDescLineEdit = QtWidgets.QLineEdit(srwrLookupDialog)
        self.typeDescLineEdit.setMinimumSize(QtCore.QSize(0, 25))
        self.typeDescLineEdit.setObjectName("typeDescLineEdit")
        self.gridLayout.addWidget(self.typeDescLineEdit, 0, 2, 1, 1)
        self.itemsListView = QtWidgets.QListView(srwrLookupDialog)
        self.itemsListView.setObjectName("itemsListView")
        self.gridLayout.addWidget(self.itemsListView, 1, 0, 1, 3)
        self.typeNoSpinBox = QtWidgets.QSpinBox(srwrLookupDialog)
        self.typeNoSpinBox.setMinimumSize(QtCore.QSize(0, 25))
        self.typeNoSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.typeNoSpinBox.setMinimum(0)
        self.typeNoSpinBox.setMaximum(999)
        self.typeNoSpinBox.setObjectName("typeNoSpinBox")
        self.gridLayout.addWidget(self.typeNoSpinBox, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.addButton = QtWidgets.QPushButton(srwrLookupDialog)
        self.addButton.setObjectName("addButton")
        self.verticalLayout_2.addWidget(self.addButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem1)
        self.removeButton = QtWidgets.QPushButton(srwrLookupDialog)
        self.removeButton.setObjectName("removeButton")
        self.verticalLayout_2.addWidget(self.removeButton)
        self.amendButton = QtWidgets.QPushButton(srwrLookupDialog)
        self.amendButton.setObjectName("amendButton")
        self.verticalLayout_2.addWidget(self.amendButton)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.closeButton = QtWidgets.QPushButton(srwrLookupDialog)
        self.closeButton.setObjectName("closeButton")
        self.verticalLayout_2.addWidget(self.closeButton)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 1, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(srwrLookupDialog)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.desRadioButton = QtWidgets.QRadioButton(self.groupBox)
        self.desRadioButton.setObjectName("desRadioButton")
        self.horizontalLayout.addWidget(self.desRadioButton)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.reinsRadioButton = QtWidgets.QRadioButton(self.groupBox)
        self.reinsRadioButton.setObjectName("reinsRadioButton")
        self.horizontalLayout.addWidget(self.reinsRadioButton)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.statRadioButton = QtWidgets.QRadioButton(self.groupBox)
        self.statRadioButton.setObjectName("statRadioButton")
        self.horizontalLayout.addWidget(self.statRadioButton)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 2)

        self.retranslateUi(srwrLookupDialog)
        QtCore.QMetaObject.connectSlotsByName(srwrLookupDialog)

    def retranslateUi(self, srwrLookupDialog):
        _translate = QtCore.QCoreApplication.translate
        srwrLookupDialog.setWindowTitle(_translate("srwrLookupDialog", "Dialog"))
        self.addButton.setText(_translate("srwrLookupDialog", "Add"))
        self.removeButton.setText(_translate("srwrLookupDialog", "Remove"))
        self.amendButton.setText(_translate("srwrLookupDialog", "Amend"))
        self.closeButton.setText(_translate("srwrLookupDialog", "Close"))
        self.groupBox.setTitle(_translate("srwrLookupDialog", "Lookup Table:"))
        self.desRadioButton.setText(_translate("srwrLookupDialog", "Special Designation"))
        self.reinsRadioButton.setText(_translate("srwrLookupDialog", "Reinstatement"))
        self.statRadioButton.setText(_translate("srwrLookupDialog", "Road Status"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    srwrLookupDialog = QtWidgets.QDialog()
    ui = Ui_srwrLookupDialog()
    ui.setupUi(srwrLookupDialog)
    srwrLookupDialog.show()
    sys.exit(app.exec_())

