# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rn_about_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_aboutDialog(object):
    def setupUi(self, aboutDialog):
        aboutDialog.setObjectName("aboutDialog")
        aboutDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        aboutDialog.setEnabled(True)
        aboutDialog.resize(438, 366)
        aboutDialog.setMinimumSize(QtCore.QSize(438, 366))
        aboutDialog.setModal(True)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(aboutDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.imageLabel = QtWidgets.QLabel(aboutDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageLabel.sizePolicy().hasHeightForWidth())
        self.imageLabel.setSizePolicy(sizePolicy)
        self.imageLabel.setMinimumSize(QtCore.QSize(126, 105))
        self.imageLabel.setMaximumSize(QtCore.QSize(126, 105))
        self.imageLabel.setSizeIncrement(QtCore.QSize(0, 0))
        self.imageLabel.setText("")
        self.imageLabel.setPixmap(QtGui.QPixmap("../image/rn_logo_v2.png"))
        self.imageLabel.setScaledContents(True)
        self.imageLabel.setObjectName("imageLabel")
        self.horizontalLayout.addWidget(self.imageLabel)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(aboutDialog)
        self.label.setMaximumSize(QtCore.QSize(110, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.versionLabel = QtWidgets.QLabel(aboutDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.versionLabel.sizePolicy().hasHeightForWidth())
        self.versionLabel.setSizePolicy(sizePolicy)
        self.versionLabel.setMaximumSize(QtCore.QSize(290, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.versionLabel.setFont(font)
        self.versionLabel.setObjectName("versionLabel")
        self.verticalLayout.addWidget(self.versionLabel)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.descLabel = QtWidgets.QLabel(aboutDialog)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(9)
        self.descLabel.setFont(font)
        self.descLabel.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.descLabel.setWordWrap(True)
        self.descLabel.setObjectName("descLabel")
        self.verticalLayout_2.addWidget(self.descLabel)
        self.gnuLicenseLabel = QtWidgets.QLabel(aboutDialog)
        self.gnuLicenseLabel.setWordWrap(True)
        self.gnuLicenseLabel.setObjectName("gnuLicenseLabel")
        self.verticalLayout_2.addWidget(self.gnuLicenseLabel)
        self.thinkWhereLinkLabel = QtWidgets.QLabel(aboutDialog)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(9)
        self.thinkWhereLinkLabel.setFont(font)
        self.thinkWhereLinkLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.thinkWhereLinkLabel.setObjectName("thinkWhereLinkLabel")
        self.verticalLayout_2.addWidget(self.thinkWhereLinkLabel)
        self.line = QtWidgets.QFrame(aboutDialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.copyrightLabel = QtWidgets.QLabel(aboutDialog)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.copyrightLabel.setFont(font)
        self.copyrightLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.copyrightLabel.setWordWrap(True)
        self.copyrightLabel.setObjectName("copyrightLabel")
        self.horizontalLayout_2.addWidget(self.copyrightLabel)
        self.okButton = QtWidgets.QPushButton(aboutDialog)
        self.okButton.setMinimumSize(QtCore.QSize(81, 23))
        self.okButton.setMaximumSize(QtCore.QSize(81, 23))
        self.okButton.setObjectName("okButton")
        self.horizontalLayout_2.addWidget(self.okButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)

        self.retranslateUi(aboutDialog)
        QtCore.QMetaObject.connectSlotsByName(aboutDialog)

    def retranslateUi(self, aboutDialog):
        _translate = QtCore.QCoreApplication.translate
        aboutDialog.setWindowTitle(_translate("aboutDialog", "About roadNet"))
        self.label.setText(_translate("aboutDialog", "roadNet"))
        self.versionLabel.setText(_translate("aboutDialog", "Version:"))
        self.descLabel.setText(_translate("aboutDialog", "roadNet is an application for managing a local street gazetteer (LSG) complying with BS7666 standards, using the conventions set out for the Scottish Gazetteer.  It also enables the creation and management of associated data (ASD) which is required by the Scottish Road Works Register. The application manages all information required by these standards, as well as additional data fields that are of use internally by local authorities.  The RAMP functions manage a register of road assets."))
        self.gnuLicenseLabel.setText(_translate("aboutDialog", "<html><head/><body><p align=\"center\">roadNet is licenced under the <a href=\"http://www.gnu.org/licenses\"><span style=\" text-decoration: underline; color:#0000ff;\">GNU General Public Licence Version 2</span></a>.</p></body></html>"))
        self.thinkWhereLinkLabel.setText(_translate("aboutDialog", "<html><head/><body><p>Visit <a href=\"http://www.thinkwhere.com\"><span style=\" text-decoration: underline; color:#0000ff;\">http://www.thinkwhere.com</span></a> for more information.</p></body></html>"))
        self.copyrightLabel.setText(_translate("aboutDialog", "Copyright thinkWhere Ltd 2016"))
        self.okButton.setText(_translate("aboutDialog", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    aboutDialog = QtWidgets.QDialog()
    ui = Ui_aboutDialog()
    ui.setupUi(aboutDialog)
    aboutDialog.show()
    sys.exit(app.exec_())

