# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rn_export_lor_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_exportLorDialog(object):
    def setupUi(self, exportLorDialog):
        exportLorDialog.setObjectName("exportLorDialog")
        exportLorDialog.resize(353, 417)
        exportLorDialog.setMinimumSize(QtCore.QSize(353, 417))
        exportLorDialog.setMaximumSize(QtCore.QSize(353, 417))
        self.gridLayout_4 = QtWidgets.QGridLayout(exportLorDialog)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fileLabel = QtWidgets.QLabel(exportLorDialog)
        self.fileLabel.setObjectName("fileLabel")
        self.horizontalLayout.addWidget(self.fileLabel)
        self.fileLineEdit = QtWidgets.QLineEdit(exportLorDialog)
        self.fileLineEdit.setObjectName("fileLineEdit")
        self.horizontalLayout.addWidget(self.fileLineEdit)
        self.openPushButton = QtWidgets.QPushButton(exportLorDialog)
        self.openPushButton.setText("")
        self.openPushButton.setObjectName("openPushButton")
        self.horizontalLayout.addWidget(self.openPushButton)
        self.gridLayout_4.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(exportLorDialog)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setWordWrap(True)
        self.label_4.setIndent(7)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(exportLorDialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.publicRadioButton = QtWidgets.QRadioButton(self.groupBox)
        self.publicRadioButton.setEnabled(True)
        self.publicRadioButton.setObjectName("publicRadioButton")
        self.horizontalLayout_10.addWidget(self.publicRadioButton)
        spacerItem1 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem1)
        self.anyRadioButton = QtWidgets.QRadioButton(self.groupBox)
        self.anyRadioButton.setObjectName("anyRadioButton")
        self.horizontalLayout_10.addWidget(self.anyRadioButton)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(27, 5, 3, 3)
        self.horizontalLayout_7.setSpacing(36)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.publicCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.publicCheckBox.setObjectName("publicCheckBox")
        self.horizontalLayout_7.addWidget(self.publicCheckBox)
        self.proPublicCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.proPublicCheckBox.setObjectName("proPublicCheckBox")
        self.horizontalLayout_7.addWidget(self.proPublicCheckBox)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(27, 5, 3, 3)
        self.horizontalLayout_11.setSpacing(36)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.t3CheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.t3CheckBox.setObjectName("t3CheckBox")
        self.horizontalLayout_11.addWidget(self.t3CheckBox)
        self.t4CheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.t4CheckBox.setObjectName("t4CheckBox")
        self.horizontalLayout_11.addWidget(self.t4CheckBox)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(27, 5, 3, 3)
        self.horizontalLayout_12.setSpacing(36)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.privateCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.privateCheckBox.setObjectName("privateCheckBox")
        self.horizontalLayout_12.addWidget(self.privateCheckBox)
        self.trunkCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.trunkCheckBox.setObjectName("trunkCheckBox")
        self.horizontalLayout_12.addWidget(self.trunkCheckBox)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 2, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(exportLorDialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(27, 5, 3, 3)
        self.horizontalLayout_8.setSpacing(36)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lorNoCeckBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.lorNoCeckBox.setObjectName("lorNoCeckBox")
        self.horizontalLayout_8.addWidget(self.lorNoCeckBox)
        self.usrnCheckBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.usrnCheckBox.setObjectName("usrnCheckBox")
        self.horizontalLayout_8.addWidget(self.usrnCheckBox)
        self.gridLayout_2.addLayout(self.horizontalLayout_8, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 3, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(exportLorDialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.townCheckBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.townCheckBox.setObjectName("townCheckBox")
        self.horizontalLayout_9.addWidget(self.townCheckBox)
        spacerItem2 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem2)
        self.csvCheckBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.csvCheckBox.setObjectName("csvCheckBox")
        self.horizontalLayout_9.addWidget(self.csvCheckBox)
        self.gridLayout_3.addLayout(self.horizontalLayout_9, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_3, 4, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(214, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.okPushButton = QtWidgets.QPushButton(exportLorDialog)
        self.okPushButton.setObjectName("okPushButton")
        self.horizontalLayout_3.addWidget(self.okPushButton)
        self.cancelPushButton = QtWidgets.QPushButton(exportLorDialog)
        self.cancelPushButton.setObjectName("cancelPushButton")
        self.horizontalLayout_3.addWidget(self.cancelPushButton)
        self.gridLayout_4.addLayout(self.horizontalLayout_3, 5, 0, 1, 1)

        self.retranslateUi(exportLorDialog)
        QtCore.QMetaObject.connectSlotsByName(exportLorDialog)

    def retranslateUi(self, exportLorDialog):
        _translate = QtCore.QCoreApplication.translate
        exportLorDialog.setWindowTitle(_translate("exportLorDialog", "Dialog"))
        self.fileLabel.setText(_translate("exportLorDialog", "Export To"))
        self.label_4.setText(_translate("exportLorDialog", "Default settings report Name, Town, Status and Description for Public Type 1 + 2 streets."))
        self.groupBox.setTitle(_translate("exportLorDialog", "Records"))
        self.publicRadioButton.setText(_translate("exportLorDialog", "Public Only"))
        self.anyRadioButton.setText(_translate("exportLorDialog", "Any Status"))
        self.publicCheckBox.setText(_translate("exportLorDialog", "Public"))
        self.proPublicCheckBox.setText(_translate("exportLorDialog", "Prospective Public"))
        self.t3CheckBox.setText(_translate("exportLorDialog", "Include Type 3"))
        self.t4CheckBox.setText(_translate("exportLorDialog", "Include Type 4"))
        self.privateCheckBox.setText(_translate("exportLorDialog", "Private"))
        self.trunkCheckBox.setText(_translate("exportLorDialog", "Trunk"))
        self.groupBox_2.setTitle(_translate("exportLorDialog", "Additional Info"))
        self.lorNoCeckBox.setText(_translate("exportLorDialog", "Include LOR No"))
        self.usrnCheckBox.setText(_translate("exportLorDialog", "USRN"))
        self.groupBox_3.setTitle(_translate("exportLorDialog", "Format Options"))
        self.townCheckBox.setText(_translate("exportLorDialog", "Sort By Town"))
        self.csvCheckBox.setText(_translate("exportLorDialog", "CSV Formatted"))
        self.okPushButton.setText(_translate("exportLorDialog", "OK"))
        self.cancelPushButton.setText(_translate("exportLorDialog", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    exportLorDialog = QtWidgets.QDialog()
    ui = Ui_exportLorDialog()
    ui.setupUi(exportLorDialog)
    exportLorDialog.show()
    sys.exit(app.exec_())

