# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rn_filter_street_record_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_filterStreetRecordDialog(object):
    def setupUi(self, filterStreetRecordDialog):
        filterStreetRecordDialog.setObjectName("filterStreetRecordDialog")
        filterStreetRecordDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        filterStreetRecordDialog.resize(813, 487)
        filterStreetRecordDialog.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(filterStreetRecordDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.mapPushButton = QtWidgets.QPushButton(filterStreetRecordDialog)
        self.mapPushButton.setObjectName("mapPushButton")
        self.gridLayout_9.addWidget(self.mapPushButton, 0, 5, 1, 1)
        self.quickFindPushButton = QtWidgets.QPushButton(filterStreetRecordDialog)
        self.quickFindPushButton.setObjectName("quickFindPushButton")
        self.gridLayout_9.addWidget(self.quickFindPushButton, 0, 2, 1, 1)
        self.gotoRecordPushButton = QtWidgets.QPushButton(filterStreetRecordDialog)
        self.gotoRecordPushButton.setObjectName("gotoRecordPushButton")
        self.gridLayout_9.addWidget(self.gotoRecordPushButton, 0, 6, 1, 1)
        self.totalSelectionLabel = QtWidgets.QLabel(filterStreetRecordDialog)
        self.totalSelectionLabel.setText("")
        self.totalSelectionLabel.setObjectName("totalSelectionLabel")
        self.gridLayout_9.addWidget(self.totalSelectionLabel, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem, 0, 3, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_9, 2, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(filterStreetRecordDialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.resultsTableView = QtWidgets.QTableView(self.groupBox_2)
        self.resultsTableView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.resultsTableView.setObjectName("resultsTableView")
        self.resultsTableView.verticalHeader().setVisible(False)
        self.gridLayout_8.addWidget(self.resultsTableView, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(filterStreetRecordDialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.localityComboBox = QtWidgets.QComboBox(self.groupBox)
        self.localityComboBox.setObjectName("localityComboBox")
        self.gridLayout_3.addWidget(self.localityComboBox, 2, 0, 1, 1)
        self.localityLabel = QtWidgets.QLabel(self.groupBox)
        self.localityLabel.setObjectName("localityLabel")
        self.gridLayout_3.addWidget(self.localityLabel, 1, 0, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_3, 0, 4, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.descriptionLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.descriptionLineEdit.setMinimumSize(QtCore.QSize(140, 0))
        self.descriptionLineEdit.setText("")
        self.descriptionLineEdit.setObjectName("descriptionLineEdit")
        self.gridLayout_2.addWidget(self.descriptionLineEdit, 1, 0, 1, 1)
        self.descriptionLabel = QtWidgets.QLabel(self.groupBox)
        self.descriptionLabel.setObjectName("descriptionLabel")
        self.gridLayout_2.addWidget(self.descriptionLabel, 0, 0, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_2, 0, 2, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.recordTypeLabel = QtWidgets.QLabel(self.groupBox)
        self.recordTypeLabel.setObjectName("recordTypeLabel")
        self.gridLayout_5.addWidget(self.recordTypeLabel, 0, 0, 1, 1)
        self.recordTypeComboBox = QtWidgets.QComboBox(self.groupBox)
        self.recordTypeComboBox.setObjectName("recordTypeComboBox")
        self.gridLayout_5.addWidget(self.recordTypeComboBox, 1, 0, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.townComboBox = QtWidgets.QComboBox(self.groupBox)
        self.townComboBox.setObjectName("townComboBox")
        self.gridLayout_4.addWidget(self.townComboBox, 1, 0, 1, 1)
        self.townLabel = QtWidgets.QLabel(self.groupBox)
        self.townLabel.setObjectName("townLabel")
        self.gridLayout_4.addWidget(self.townLabel, 0, 0, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_4, 0, 5, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.stateLabel = QtWidgets.QLabel(self.groupBox)
        self.stateLabel.setObjectName("stateLabel")
        self.gridLayout_6.addWidget(self.stateLabel, 0, 0, 1, 1)
        self.stateComboBox = QtWidgets.QComboBox(self.groupBox)
        self.stateComboBox.setObjectName("stateComboBox")
        self.gridLayout_6.addWidget(self.stateComboBox, 1, 0, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_6, 0, 3, 1, 1)
        self.clearPushButton = QtWidgets.QPushButton(self.groupBox)
        self.clearPushButton.setObjectName("clearPushButton")
        self.gridLayout_10.addWidget(self.clearPushButton, 0, 6, 1, 1, QtCore.Qt.AlignBottom)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(filterStreetRecordDialog)
        QtCore.QMetaObject.connectSlotsByName(filterStreetRecordDialog)

    def retranslateUi(self, filterStreetRecordDialog):
        _translate = QtCore.QCoreApplication.translate
        filterStreetRecordDialog.setWindowTitle(_translate("filterStreetRecordDialog", "roadNet - Filter Street Records"))
        self.mapPushButton.setText(_translate("filterStreetRecordDialog", "Map"))
        self.quickFindPushButton.setText(_translate("filterStreetRecordDialog", "Quick Find"))
        self.gotoRecordPushButton.setText(_translate("filterStreetRecordDialog", "Goto Record"))
        self.groupBox_2.setTitle(_translate("filterStreetRecordDialog", "Selection Results"))
        self.groupBox.setTitle(_translate("filterStreetRecordDialog", "Selection Criteria"))
        self.localityLabel.setText(_translate("filterStreetRecordDialog", "Locality"))
        self.descriptionLabel.setText(_translate("filterStreetRecordDialog", "Description"))
        self.recordTypeLabel.setText(_translate("filterStreetRecordDialog", "Street Type"))
        self.townLabel.setText(_translate("filterStreetRecordDialog", "Town"))
        self.stateLabel.setText(_translate("filterStreetRecordDialog", "State"))
        self.clearPushButton.setText(_translate("filterStreetRecordDialog", "Clear"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    filterStreetRecordDialog = QtWidgets.QDialog()
    ui = Ui_filterStreetRecordDialog()
    ui.setupUi(filterStreetRecordDialog)
    filterStreetRecordDialog.show()
    sys.exit(app.exec_())

