# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rn_street_browser_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_streetBrowserDialog(object):
    def setupUi(self, streetBrowserDialog):
        streetBrowserDialog.setObjectName("streetBrowserDialog")
        streetBrowserDialog.resize(1212, 650)
        streetBrowserDialog.setMinimumSize(QtCore.QSize(1212, 650))
        streetBrowserDialog.setMaximumSize(QtCore.QSize(16777215, 16777215))
        streetBrowserDialog.setBaseSize(QtCore.QSize(1212, 700))
        self.gridLayout_32 = QtWidgets.QGridLayout(streetBrowserDialog)
        self.gridLayout_32.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_32.setSpacing(0)
        self.gridLayout_32.setObjectName("gridLayout_32")
        self.scrollArea = QtWidgets.QScrollArea(streetBrowserDialog)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1195, 1001))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_34 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_34.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_34.setSpacing(6)
        self.gridLayout_34.setObjectName("gridLayout_34")
        self.srwrRecordsGroupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.srwrRecordsGroupBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.srwrRecordsGroupBox.sizePolicy().hasHeightForWidth())
        self.srwrRecordsGroupBox.setSizePolicy(sizePolicy)
        self.srwrRecordsGroupBox.setMinimumSize(QtCore.QSize(861, 0))
        self.srwrRecordsGroupBox.setObjectName("srwrRecordsGroupBox")
        self.gridLayout_33 = QtWidgets.QGridLayout(self.srwrRecordsGroupBox)
        self.gridLayout_33.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_33.setSpacing(6)
        self.gridLayout_33.setObjectName("gridLayout_33")
        self.srwrTabWidget = QtWidgets.QTabWidget(self.srwrRecordsGroupBox)
        self.srwrTabWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.srwrTabWidget.sizePolicy().hasHeightForWidth())
        self.srwrTabWidget.setSizePolicy(sizePolicy)
        self.srwrTabWidget.setMinimumSize(QtCore.QSize(0, 250))
        self.srwrTabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.srwrTabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.srwrTabWidget.setIconSize(QtCore.QSize(16, 16))
        self.srwrTabWidget.setUsesScrollButtons(True)
        self.srwrTabWidget.setDocumentMode(False)
        self.srwrTabWidget.setObjectName("srwrTabWidget")
        self.maintenanceTab = QtWidgets.QWidget()
        self.maintenanceTab.setObjectName("maintenanceTab")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.maintenanceTab)
        self.gridLayout_13.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_13.setSpacing(6)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.maintTableView = QtWidgets.QTableView(self.maintenanceTab)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.maintTableView.setFont(font)
        self.maintTableView.setStyleSheet("border-width:0.5px;\n"
"border-style: solid;\n"
"border-radius: 2px;\n"
"border-color:  rgb(100,100,100);\n"
"background-color: rgb(213, 234, 234);")
        self.maintTableView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.maintTableView.setAlternatingRowColors(False)
        self.maintTableView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.maintTableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.maintTableView.setObjectName("maintTableView")
        self.maintTableView.horizontalHeader().setStretchLastSection(True)
        self.maintTableView.verticalHeader().setVisible(False)
        self.gridLayout_13.addWidget(self.maintTableView, 0, 0, 1, 1)
        self.srwrTabWidget.addTab(self.maintenanceTab, "")
        self.specialDesignationsTab = QtWidgets.QWidget()
        self.specialDesignationsTab.setObjectName("specialDesignationsTab")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.specialDesignationsTab)
        self.gridLayout_16.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_16.setSpacing(6)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.specDesTableView = QtWidgets.QTableView(self.specialDesignationsTab)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.specDesTableView.setFont(font)
        self.specDesTableView.setStyleSheet("border-width:0.5px;\n"
"border-style: solid;\n"
"border-radius: 2px;\n"
"border-color:  rgb(100,100,100);\n"
"background-color: rgb(213, 234, 234);")
        self.specDesTableView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.specDesTableView.setAlternatingRowColors(False)
        self.specDesTableView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.specDesTableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.specDesTableView.setObjectName("specDesTableView")
        self.specDesTableView.horizontalHeader().setStretchLastSection(True)
        self.specDesTableView.verticalHeader().setVisible(False)
        self.gridLayout_16.addWidget(self.specDesTableView, 0, 0, 1, 1)
        self.srwrTabWidget.addTab(self.specialDesignationsTab, "")
        self.reinstatementCatsTab = QtWidgets.QWidget()
        self.reinstatementCatsTab.setObjectName("reinstatementCatsTab")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.reinstatementCatsTab)
        self.gridLayout_17.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_17.setSpacing(6)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.reinstCatTableView = QtWidgets.QTableView(self.reinstatementCatsTab)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.reinstCatTableView.setFont(font)
        self.reinstCatTableView.setStyleSheet("border-width:0.5px;\n"
"border-style: solid;\n"
"border-radius: 2px;\n"
"border-color:  rgb(100,100,100);\n"
"background-color: rgb(213, 234, 234);")
        self.reinstCatTableView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.reinstCatTableView.setAlternatingRowColors(False)
        self.reinstCatTableView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.reinstCatTableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.reinstCatTableView.setObjectName("reinstCatTableView")
        self.reinstCatTableView.horizontalHeader().setStretchLastSection(True)
        self.reinstCatTableView.verticalHeader().setVisible(False)
        self.gridLayout_17.addWidget(self.reinstCatTableView, 0, 0, 1, 1)
        self.srwrTabWidget.addTab(self.reinstatementCatsTab, "")
        self.gridLayout_33.addWidget(self.srwrTabWidget, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.srwrRecordsGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_14.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_14.setSpacing(6)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.srwrAddPushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.srwrAddPushButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.srwrAddPushButton.setObjectName("srwrAddPushButton")
        self.gridLayout_14.addWidget(self.srwrAddPushButton, 0, 0, 1, 1)
        self.srwrModifyPushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.srwrModifyPushButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.srwrModifyPushButton.setObjectName("srwrModifyPushButton")
        self.gridLayout_14.addWidget(self.srwrModifyPushButton, 0, 1, 1, 1)
        self.srwrDeletePushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.srwrDeletePushButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.srwrDeletePushButton.setObjectName("srwrDeletePushButton")
        self.gridLayout_14.addWidget(self.srwrDeletePushButton, 0, 2, 1, 1)
        self.srwrViewPushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.srwrViewPushButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.srwrViewPushButton.setObjectName("srwrViewPushButton")
        self.gridLayout_14.addWidget(self.srwrViewPushButton, 0, 3, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBox_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.srwrExtentPushButton = QtWidgets.QPushButton(self.srwrRecordsGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.srwrExtentPushButton.sizePolicy().hasHeightForWidth())
        self.srwrExtentPushButton.setSizePolicy(sizePolicy)
        self.srwrExtentPushButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.srwrExtentPushButton.setObjectName("srwrExtentPushButton")
        self.horizontalLayout_2.addWidget(self.srwrExtentPushButton)
        self.gridLayout_33.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.gridLayout_34.addWidget(self.srwrRecordsGroupBox, 1, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_3.setMinimumSize(QtCore.QSize(1141, 630))
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_12.setContentsMargins(11, 5, 11, 11)
        self.gridLayout_12.setSpacing(6)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setContentsMargins(11, 30, 11, 11)
        self.horizontalLayout_24.setSpacing(6)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem1)
        self.srwrPushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.srwrPushButton.setMaximumSize(QtCore.QSize(130, 16777215))
        self.srwrPushButton.setObjectName("srwrPushButton")
        self.horizontalLayout_24.addWidget(self.srwrPushButton)
        self.gridLayout_12.addLayout(self.horizontalLayout_24, 5, 1, 1, 1)
        self.operationsGroupBox = QtWidgets.QGroupBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.operationsGroupBox.sizePolicy().hasHeightForWidth())
        self.operationsGroupBox.setSizePolicy(sizePolicy)
        self.operationsGroupBox.setMinimumSize(QtCore.QSize(421, 56))
        self.operationsGroupBox.setObjectName("operationsGroupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.operationsGroupBox)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.addPushButton = QtWidgets.QPushButton(self.operationsGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addPushButton.sizePolicy().hasHeightForWidth())
        self.addPushButton.setSizePolicy(sizePolicy)
        self.addPushButton.setMaximumSize(QtCore.QSize(120, 16777215))
        self.addPushButton.setObjectName("addPushButton")
        self.gridLayout_3.addWidget(self.addPushButton, 0, 0, 1, 1)
        self.modifyPushButton = QtWidgets.QPushButton(self.operationsGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modifyPushButton.sizePolicy().hasHeightForWidth())
        self.modifyPushButton.setSizePolicy(sizePolicy)
        self.modifyPushButton.setMaximumSize(QtCore.QSize(120, 16777215))
        self.modifyPushButton.setObjectName("modifyPushButton")
        self.gridLayout_3.addWidget(self.modifyPushButton, 0, 1, 1, 1)
        self.closeOpPushButton = QtWidgets.QPushButton(self.operationsGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closeOpPushButton.sizePolicy().hasHeightForWidth())
        self.closeOpPushButton.setSizePolicy(sizePolicy)
        self.closeOpPushButton.setMaximumSize(QtCore.QSize(120, 16777215))
        self.closeOpPushButton.setObjectName("closeOpPushButton")
        self.gridLayout_3.addWidget(self.closeOpPushButton, 0, 2, 1, 1)
        self.filterPushButton = QtWidgets.QPushButton(self.operationsGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filterPushButton.sizePolicy().hasHeightForWidth())
        self.filterPushButton.setSizePolicy(sizePolicy)
        self.filterPushButton.setMaximumSize(QtCore.QSize(120, 16777215))
        self.filterPushButton.setObjectName("filterPushButton")
        self.gridLayout_3.addWidget(self.filterPushButton, 0, 3, 1, 1)
        self.mapPushButton = QtWidgets.QPushButton(self.operationsGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mapPushButton.sizePolicy().hasHeightForWidth())
        self.mapPushButton.setSizePolicy(sizePolicy)
        self.mapPushButton.setMaximumSize(QtCore.QSize(120, 16777215))
        self.mapPushButton.setObjectName("mapPushButton")
        self.gridLayout_3.addWidget(self.mapPushButton, 0, 4, 1, 1)
        self.gridLayout_12.addWidget(self.operationsGroupBox, 0, 1, 1, 1)
        self.LsgRecordGroupBox = QtWidgets.QGroupBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LsgRecordGroupBox.sizePolicy().hasHeightForWidth())
        self.LsgRecordGroupBox.setSizePolicy(sizePolicy)
        self.LsgRecordGroupBox.setMinimumSize(QtCore.QSize(401, 311))
        self.LsgRecordGroupBox.setMaximumSize(QtCore.QSize(16777215, 351))
        self.LsgRecordGroupBox.setSizeIncrement(QtCore.QSize(0, 0))
        self.LsgRecordGroupBox.setBaseSize(QtCore.QSize(0, 0))
        self.LsgRecordGroupBox.setObjectName("LsgRecordGroupBox")
        self.gridLayout_28 = QtWidgets.QGridLayout(self.LsgRecordGroupBox)
        self.gridLayout_28.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_28.setSpacing(6)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.descriptionLabel = QtWidgets.QLabel(self.LsgRecordGroupBox)
        self.descriptionLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.descriptionLabel.setObjectName("descriptionLabel")
        self.horizontalLayout_6.addWidget(self.descriptionLabel)
        spacerItem2 = QtWidgets.QSpacerItem(8, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.descriptionTextEdit = QtWidgets.QTextEdit(self.LsgRecordGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.descriptionTextEdit.sizePolicy().hasHeightForWidth())
        self.descriptionTextEdit.setSizePolicy(sizePolicy)
        self.descriptionTextEdit.setMinimumSize(QtCore.QSize(0, 40))
        self.descriptionTextEdit.setMaximumSize(QtCore.QSize(16777215, 50))
        self.descriptionTextEdit.setStyleSheet("border-width:0.5px;\n"
"border-style: solid;\n"
"border-radius: 2px;\n"
"border-color:  rgb(100,100,100);\n"
"background-color: rgb(213, 234, 234);")
        self.descriptionTextEdit.setReadOnly(True)
        self.descriptionTextEdit.setObjectName("descriptionTextEdit")
        self.horizontalLayout_6.addWidget(self.descriptionTextEdit)
        self.gridLayout_28.addLayout(self.horizontalLayout_6, 2, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.localityLabel = QtWidgets.QLabel(self.LsgRecordGroupBox)
        self.localityLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.localityLabel.setObjectName("localityLabel")
        self.horizontalLayout_7.addWidget(self.localityLabel)
        self.localityStackedWidget = QtWidgets.QStackedWidget(self.LsgRecordGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.localityStackedWidget.sizePolicy().hasHeightForWidth())
        self.localityStackedWidget.setSizePolicy(sizePolicy)
        self.localityStackedWidget.setMinimumSize(QtCore.QSize(290, 20))
        self.localityStackedWidget.setObjectName("localityStackedWidget")
        self.localityReadOnlyPage = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.localityReadOnlyPage.sizePolicy().hasHeightForWidth())
        self.localityReadOnlyPage.setSizePolicy(sizePolicy)
        self.localityReadOnlyPage.setMinimumSize(QtCore.QSize(290, 20))
        self.localityReadOnlyPage.setObjectName("localityReadOnlyPage")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.localityReadOnlyPage)
        self.gridLayout_6.setContentsMargins(27, 0, 0, 0)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.localityLineEdit = QtWidgets.QLineEdit(self.localityReadOnlyPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.localityLineEdit.sizePolicy().hasHeightForWidth())
        self.localityLineEdit.setSizePolicy(sizePolicy)
        self.localityLineEdit.setMinimumSize(QtCore.QSize(278, 20))
        self.localityLineEdit.setMaximumSize(QtCore.QSize(16777215, 20))
        self.localityLineEdit.setStyleSheet("border-width:0.5px;\n"
"border-style: solid;\n"
"border-radius: 2px;\n"
"border-color:  rgb(100,100,100);\n"
"background-color: rgb(213, 234, 234);")
        self.localityLineEdit.setReadOnly(True)
        self.localityLineEdit.setObjectName("localityLineEdit")
        self.gridLayout_6.addWidget(self.localityLineEdit, 0, 0, 1, 1)
        self.localityStackedWidget.addWidget(self.localityReadOnlyPage)
        self.localityModifyPage = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.localityModifyPage.sizePolicy().hasHeightForWidth())
        self.localityModifyPage.setSizePolicy(sizePolicy)
        self.localityModifyPage.setMinimumSize(QtCore.QSize(290, 20))
        self.localityModifyPage.setObjectName("localityModifyPage")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.localityModifyPage)
        self.gridLayout_8.setContentsMargins(27, 0, 0, 0)
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.localityComboBox = QtWidgets.QComboBox(self.localityModifyPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.localityComboBox.sizePolicy().hasHeightForWidth())
        self.localityComboBox.setSizePolicy(sizePolicy)
        self.localityComboBox.setMinimumSize(QtCore.QSize(278, 20))
        self.localityComboBox.setMaximumSize(QtCore.QSize(16777215, 20))
        self.localityComboBox.setObjectName("localityComboBox")
        self.gridLayout_8.addWidget(self.localityComboBox, 0, 0, 1, 1)
        self.localityStackedWidget.addWidget(self.localityModifyPage)
        self.horizontalLayout_7.addWidget(self.localityStackedWidget)
        self.gridLayout_28.addLayout(self.horizontalLayout_7, 3, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.townLabel = QtWidgets.QLabel(self.LsgRecordGroupBox)
        self.townLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.townLabel.setObjectName("townLabel")
        self.horizontalLayout_8.addWidget(self.townLabel)
        self.townStackedWidget = QtWidgets.QStackedWidget(self.LsgRecordGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.townStackedWidget.sizePolicy().hasHeightForWidth())
        self.townStackedWidget.setSizePolicy(sizePolicy)
        self.townStackedWidget.setMinimumSize(QtCore.QSize(290, 20))
        self.townStackedWidget.setObjectName("townStackedWidget")
        self.townReadOnlyPage = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.townReadOnlyPage.sizePolicy().hasHeightForWidth())
        self.townReadOnlyPage.setSizePolicy(sizePolicy)
        self.townReadOnlyPage.setMinimumSize(QtCore.QSize(290, 20))
        self.townReadOnlyPage.setObjectName("townReadOnlyPage")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.townReadOnlyPage)
        self.gridLayout_9.setContentsMargins(31, 0, 0, 0)
        self.gridLayout_9.setSpacing(0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.townLineEdit = QtWidgets.QLineEdit(self.townReadOnlyPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.townLineEdit.sizePolicy().hasHeightForWidth())
        self.townLineEdit.setSizePolicy(sizePolicy)
        self.townLineEdit.setMinimumSize(QtCore.QSize(278, 20))
        self.townLineEdit.setMaximumSize(QtCore.QSize(16777215, 20))
        self.townLineEdit.setStyleSheet("border-width:0.5px;\n"
"border-style: solid;\n"
"border-radius: 2px;\n"
"border-color:  rgb(100,100,100);\n"
"background-color: rgb(213, 234, 234);")
        self.townLineEdit.setReadOnly(True)
        self.townLineEdit.setObjectName("townLineEdit")
        self.gridLayout_9.addWidget(self.townLineEdit, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(6, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem3, 0, 0, 1, 1)
        self.townStackedWidget.addWidget(self.townReadOnlyPage)
        self.townModifyPage = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.townModifyPage.sizePolicy().hasHeightForWidth())
        self.townModifyPage.setSizePolicy(sizePolicy)
        self.townModifyPage.setMinimumSize(QtCore.QSize(290, 20))
        self.townModifyPage.setObjectName("townModifyPage")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.townModifyPage)
        self.gridLayout_10.setContentsMargins(31, 0, 0, 0)
        self.gridLayout_10.setSpacing(0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.townComboBox = QtWidgets.QComboBox(self.townModifyPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.townComboBox.sizePolicy().hasHeightForWidth())
        self.townComboBox.setSizePolicy(sizePolicy)
        self.townComboBox.setMinimumSize(QtCore.QSize(278, 20))
        self.townComboBox.setMaximumSize(QtCore.QSize(16777215, 20))
        self.townComboBox.setObjectName("townComboBox")
        self.gridLayout_10.addWidget(self.townComboBox, 0, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(6, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem4, 0, 0, 1, 1)
        self.townStackedWidget.addWidget(self.townModifyPage)
        self.horizontalLayout_8.addWidget(self.townStackedWidget)
        self.gridLayout_28.addLayout(self.horizontalLayout_8, 4, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.typeLabel = QtWidgets.QLabel(self.LsgRecordGroupBox)
        self.typeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.typeLabel.setObjectName("typeLabel")
        self.horizontalLayout_5.addWidget(self.typeLabel)
        spacerItem5 = QtWidgets.QSpacerItem(7, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.typeStackedWidget = QtWidgets.QStackedWidget(self.LsgRecordGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.typeStackedWidget.sizePolicy().hasHeightForWidth())
        self.typeStackedWidget.setSizePolicy(sizePolicy)
        self.typeStackedWidget.setMinimumSize(QtCore.QSize(278, 20))
        self.typeStackedWidget.setObjectName("typeStackedWidget")
        self.typeReadOnlyPage = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.typeReadOnlyPage.sizePolicy().hasHeightForWidth())
        self.typeReadOnlyPage.setSizePolicy(sizePolicy)
        self.typeReadOnlyPage.setMinimumSize(QtCore.QSize(290, 20))
        self.typeReadOnlyPage.setObjectName("typeReadOnlyPage")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.typeReadOnlyPage)
        self.gridLayout_5.setContentsMargins(32, 0, 0, 0)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.typeLineEdit = QtWidgets.QLineEdit(self.typeReadOnlyPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.typeLineEdit.sizePolicy().hasHeightForWidth())
        self.typeLineEdit.setSizePolicy(sizePolicy)
        self.typeLineEdit.setMinimumSize(QtCore.QSize(278, 20))
        self.typeLineEdit.setMaximumSize(QtCore.QSize(99999, 20))
        self.typeLineEdit.setStyleSheet("border-width:0.5px;\n"
"border-style: solid;\n"
"border-radius: 2px;\n"
"border-color:  rgb(100,100,100);\n"
"background-color: rgb(213, 234, 234);")
        self.typeLineEdit.setReadOnly(True)
        self.typeLineEdit.setObjectName("typeLineEdit")
        self.gridLayout_5.addWidget(self.typeLineEdit, 0, 0, 1, 1)
        self.typeStackedWidget.addWidget(self.typeReadOnlyPage)
        self.typeModifyPage = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.typeModifyPage.sizePolicy().hasHeightForWidth())
        self.typeModifyPage.setSizePolicy(sizePolicy)
        self.typeModifyPage.setMinimumSize(QtCore.QSize(290, 20))
        self.typeModifyPage.setObjectName("typeModifyPage")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.typeModifyPage)
        self.gridLayout_4.setContentsMargins(32, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.recordTypeComboBox = QtWidgets.QComboBox(self.typeModifyPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.recordTypeComboBox.sizePolicy().hasHeightForWidth())
        self.recordTypeComboBox.setSizePolicy(sizePolicy)
        self.recordTypeComboBox.setMinimumSize(QtCore.QSize(278, 20))
        self.recordTypeComboBox.setMaximumSize(QtCore.QSize(16777215, 20))
        self.recordTypeComboBox.setObjectName("recordTypeComboBox")
        self.gridLayout_4.addWidget(self.recordTypeComboBox, 0, 0, 1, 1)
        self.typeStackedWidget.addWidget(self.typeModifyPage)
        self.horizontalLayout_5.addWidget(self.typeStackedWidget)
        self.gridLayout_28.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.startDateLabel = QtWidgets.QLabel(self.LsgRecordGroupBox)
        self.startDateLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.startDateLabel.setObjectName("startDateLabel")
        self.horizontalLayout.addWidget(self.startDateLabel)
        spacerItem6 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.startDateStackedWidget = QtWidgets.QStackedWidget(self.LsgRecordGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startDateStackedWidget.sizePolicy().hasHeightForWidth())
        self.startDateStackedWidget.setSizePolicy(sizePolicy)
        self.startDateStackedWidget.setMinimumSize(QtCore.QSize(126, 20))
        self.startDateStackedWidget.setMaximumSize(QtCore.QSize(126, 20))
        self.startDateStackedWidget.setObjectName("startDateStackedWidget")
        self.startDateReadOnlyPage = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startDateReadOnlyPage.sizePolicy().hasHeightForWidth())
        self.startDateReadOnlyPage.setSizePolicy(sizePolicy)
        self.startDateReadOnlyPage.setMinimumSize(QtCore.QSize(80, 20))
        self.startDateReadOnlyPage.setObjectName("startDateReadOnlyPage")
        self.gridLayout = QtWidgets.QGridLayout(self.startDateReadOnlyPage)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.startDateLineEdit = QtWidgets.QLineEdit(self.startDateReadOnlyPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startDateLineEdit.sizePolicy().hasHeightForWidth())
        self.startDateLineEdit.setSizePolicy(sizePolicy)
        self.startDateLineEdit.setMinimumSize(QtCore.QSize(126, 20))
        self.startDateLineEdit.setMaximumSize(QtCore.QSize(126, 20))
        self.startDateLineEdit.setStyleSheet("border-width:0.5px;\n"
"border-style: solid;\n"
"border-radius: 2px;\n"
"border-color:  rgb(100,100,100);\n"
"background-color: rgb(213, 234, 234);")
        self.startDateLineEdit.setReadOnly(True)
        self.startDateLineEdit.setObjectName("startDateLineEdit")
        self.gridLayout.addWidget(self.startDateLineEdit, 0, 0, 1, 1)
        self.startDateStackedWidget.addWidget(self.startDateReadOnlyPage)
        self.startDateModifyPage = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startDateModifyPage.sizePolicy().hasHeightForWidth())
        self.startDateModifyPage.setSizePolicy(sizePolicy)
        self.startDateModifyPage.setMinimumSize(QtCore.QSize(80, 20))
        self.startDateModifyPage.setObjectName("startDateModifyPage")
        self.gridLayout_27 = QtWidgets.QGridLayout(self.startDateModifyPage)
        self.gridLayout_27.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_27.setSpacing(0)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.startDateDateEdit = QtWidgets.QDateEdit(self.startDateModifyPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startDateDateEdit.sizePolicy().hasHeightForWidth())
        self.startDateDateEdit.setSizePolicy(sizePolicy)
        self.startDateDateEdit.setMinimumSize(QtCore.QSize(126, 20))
        self.startDateDateEdit.setMaximumSize(QtCore.QSize(16777215, 20))
        self.startDateDateEdit.setCalendarPopup(True)
        self.startDateDateEdit.setObjectName("startDateDateEdit")
        self.gridLayout_27.addWidget(self.startDateDateEdit, 0, 0, 1, 1)
        self.startDateStackedWidget.addWidget(self.startDateModifyPage)
        self.horizontalLayout.addWidget(self.startDateStackedWidget)
        spacerItem7 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.entryDateLabel = QtWidgets.QLabel(self.LsgRecordGroupBox)
        self.entryDateLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.entryDateLabel.setObjectName("entryDateLabel")
        self.horizontalLayout.addWidget(self.entryDateLabel)
        spacerItem8 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem8)
        self.entryDateLineEdit = QtWidgets.QLineEdit(self.LsgRecordGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entryDateLineEdit.sizePolicy().hasHeightForWidth())
        self.entryDateLineEdit.setSizePolicy(sizePolicy)
        self.entryDateLineEdit.setMinimumSize(QtCore.QSize(126, 20))
        self.entryDateLineEdit.setMaximumSize(QtCore.QSize(126, 20))
        self.entryDateLineEdit.setStyleSheet("border-width:0.5px;\n"
"border-style: solid;\n"
"border-radius: 2px;\n"
"border-color:  rgb(100,100,100);\n"
"background-color: rgb(213, 234, 234);")
        self.entryDateLineEdit.setReadOnly(True)
        self.entryDateLineEdit.setObjectName("entryDateLineEdit")
        self.horizontalLayout.addWidget(self.entryDateLineEdit)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem9)
        self.gridLayout_28.addLayout(self.horizontalLayout, 8, 0, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.lastUpdateLabel = QtWidgets.QLabel(self.LsgRecordGroupBox)
        self.lastUpdateLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lastUpdateLabel.setObjectName("lastUpdateLabel")
        self.horizontalLayout_12.addWidget(self.lastUpdateLabel)
        spacerItem10 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem10)
        self.updateDateLineEdit = QtWidgets.QLineEdit(self.LsgRecordGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.updateDateLineEdit.sizePolicy().hasHeightForWidth())
        self.updateDateLineEdit.setSizePolicy(sizePolicy)
        self.updateDateLineEdit.setMinimumSize(QtCore.QSize(126, 20))
        self.updateDateLineEdit.setMaximumSize(QtCore.QSize(126, 20))
        self.updateDateLineEdit.setStyleSheet("border-width:0.5px;\n"
"border-style: solid;\n"
"border-radius: 2px;\n"
"border-color:  rgb(100,100,100);\n"
"background-color: rgb(213, 234, 234);")
        self.updateDateLineEdit.setObjectName("updateDateLineEdit")
        self.horizontalLayout_12.addWidget(self.updateDateLineEdit)
        spacerItem11 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem11)
        self.byLabel = QtWidgets.QLabel(self.LsgRecordGroupBox)
        self.byLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.byLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.byLabel.setObjectName("byLabel")
        self.horizontalLayout_12.addWidget(self.byLabel)
        spacerItem12 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem12)
        self.byLineEdit = QtWidgets.QLineEdit(self.LsgRecordGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.byLineEdit.sizePolicy().hasHeightForWidth())
        self.byLineEdit.setSizePolicy(sizePolicy)
        self.byLineEdit.setMinimumSize(QtCore.QSize(106, 20))
        self.byLineEdit.setMaximumSize(QtCore.QSize(16777215, 20))
        self.byLineEdit.setStyleSheet("border-width:0.5px;\n"
"border-style: solid;\n"
"border-radius: 2px;\n"
"border-color:  rgb(100,100,100);\n"
"background-color: rgb(213, 234, 234);")
        self.byLineEdit.setReadOnly(True)
        self.byLineEdit.setObjectName("byLineEdit")
        self.horizontalLayout_12.addWidget(self.byLineEdit)
        self.gridLayout_28.addLayout(self.horizontalLayout_12, 7, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.countyLabel = QtWidgets.QLabel(self.LsgRecordGroupBox)
        self.countyLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.countyLabel.setObjectName("countyLabel")
        self.horizontalLayout_9.addWidget(self.countyLabel)
        self.countyStackedWidget = QtWidgets.QStackedWidget(self.LsgRecordGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.countyStackedWidget.sizePolicy().hasHeightForWidth())
        self.countyStackedWidget.setSizePolicy(sizePolicy)
        self.countyStackedWidget.setMinimumSize(QtCore.QSize(290, 20))
        self.countyStackedWidget.setObjectName("countyStackedWidget")
        self.countyReadOnlyPage = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.countyReadOnlyPage.sizePolicy().hasHeightForWidth())
        self.countyReadOnlyPage.setSizePolicy(sizePolicy)
        self.countyReadOnlyPage.setMinimumSize(QtCore.QSize(290, 20))
        self.countyReadOnlyPage.setObjectName("countyReadOnlyPage")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.countyReadOnlyPage)
        self.gridLayout_11.setContentsMargins(22, 0, 0, 0)
        self.gridLayout_11.setSpacing(0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.countyLineEdit = QtWidgets.QLineEdit(self.countyReadOnlyPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.countyLineEdit.sizePolicy().hasHeightForWidth())
        self.countyLineEdit.setSizePolicy(sizePolicy)
        self.countyLineEdit.setMinimumSize(QtCore.QSize(278, 20))
        self.countyLineEdit.setMaximumSize(QtCore.QSize(16777215, 20))
        self.countyLineEdit.setStyleSheet("border-width:0.5px;\n"
"border-style: solid;\n"
"border-radius: 2px;\n"
"border-color:  rgb(100,100,100);\n"
"background-color: rgb(213, 234, 234);")
        self.countyLineEdit.setReadOnly(True)
        self.countyLineEdit.setObjectName("countyLineEdit")
        self.gridLayout_11.addWidget(self.countyLineEdit, 0, 1, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(6, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem13, 0, 0, 1, 1)
        self.countyStackedWidget.addWidget(self.countyReadOnlyPage)
        self.countyModifyPage = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.countyModifyPage.sizePolicy().hasHeightForWidth())
        self.countyModifyPage.setSizePolicy(sizePolicy)
        self.countyModifyPage.setMinimumSize(QtCore.QSize(290, 20))
        self.countyModifyPage.setObjectName("countyModifyPage")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.countyModifyPage)
        self.gridLayout_18.setContentsMargins(22, 0, 0, 0)
        self.gridLayout_18.setSpacing(0)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.countyComboBox = QtWidgets.QComboBox(self.countyModifyPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.countyComboBox.sizePolicy().hasHeightForWidth())
        self.countyComboBox.setSizePolicy(sizePolicy)
        self.countyComboBox.setMinimumSize(QtCore.QSize(278, 20))
        self.countyComboBox.setMaximumSize(QtCore.QSize(16777215, 20))
        self.countyComboBox.setObjectName("countyComboBox")
        self.gridLayout_18.addWidget(self.countyComboBox, 0, 1, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(6, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_18.addItem(spacerItem14, 0, 0, 1, 1)
        self.countyStackedWidget.addWidget(self.countyModifyPage)
        self.horizontalLayout_9.addWidget(self.countyStackedWidget)
        self.gridLayout_28.addLayout(self.horizontalLayout_9, 5, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.usrnLabel_2 = QtWidgets.QLabel(self.LsgRecordGroupBox)
        self.usrnLabel_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.usrnLabel_2.setObjectName("usrnLabel_2")
        self.horizontalLayout_4.addWidget(self.usrnLabel_2)
        spacerItem15 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem15)
        self.usrnLineEdit = QtWidgets.QLineEdit(self.LsgRecordGroupBox)
        self.usrnLineEdit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.usrnLineEdit.sizePolicy().hasHeightForWidth())
        self.usrnLineEdit.setSizePolicy(sizePolicy)
        self.usrnLineEdit.setMinimumSize(QtCore.QSize(126, 20))
        self.usrnLineEdit.setMaximumSize(QtCore.QSize(126, 20))
        self.usrnLineEdit.setStyleSheet("border-width:0.5px;\n"
"border-style: solid;\n"
"border-radius: 2px;\n"
"border-color:  rgb(100,100,100);\n"
"background-color: rgb(213, 234, 234);")
        self.usrnLineEdit.setReadOnly(True)
        self.usrnLineEdit.setObjectName("usrnLineEdit")
        self.horizontalLayout_4.addWidget(self.usrnLineEdit)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem16)
        self.versionLabel = QtWidgets.QLabel(self.LsgRecordGroupBox)
        self.versionLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.versionLabel.setObjectName("versionLabel")
        self.horizontalLayout_4.addWidget(self.versionLabel)
        self.versionLineEdit = QtWidgets.QLineEdit(self.LsgRecordGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.versionLineEdit.sizePolicy().hasHeightForWidth())
        self.versionLineEdit.setSizePolicy(sizePolicy)
        self.versionLineEdit.setMinimumSize(QtCore.QSize(0, 20))
        self.versionLineEdit.setMaximumSize(QtCore.QSize(40, 20))
        self.versionLineEdit.setStyleSheet("border-width:0.5px;\n"
"border-style: solid;\n"
"border-radius: 2px;\n"
"border-color:  rgb(100,100,100);\n"
"background-color: rgb(213, 234, 234);")
        self.versionLineEdit.setReadOnly(True)
        self.versionLineEdit.setObjectName("versionLineEdit")
        self.horizontalLayout_4.addWidget(self.versionLineEdit)
        self.gridLayout_28.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.authorityLabel = QtWidgets.QLabel(self.LsgRecordGroupBox)
        self.authorityLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.authorityLabel.setObjectName("authorityLabel")
        self.horizontalLayout_10.addWidget(self.authorityLabel)
        self.authorityStackedWidget = QtWidgets.QStackedWidget(self.LsgRecordGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.authorityStackedWidget.sizePolicy().hasHeightForWidth())
        self.authorityStackedWidget.setSizePolicy(sizePolicy)
        self.authorityStackedWidget.setMinimumSize(QtCore.QSize(290, 20))
        self.authorityStackedWidget.setObjectName("authorityStackedWidget")
        self.authorityReadOnlyPage = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.authorityReadOnlyPage.sizePolicy().hasHeightForWidth())
        self.authorityReadOnlyPage.setSizePolicy(sizePolicy)
        self.authorityReadOnlyPage.setMinimumSize(QtCore.QSize(290, 20))
        self.authorityReadOnlyPage.setObjectName("authorityReadOnlyPage")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.authorityReadOnlyPage)
        self.gridLayout_19.setContentsMargins(12, 0, 0, 0)
        self.gridLayout_19.setSpacing(0)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.authorityLineEdit = QtWidgets.QLineEdit(self.authorityReadOnlyPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.authorityLineEdit.sizePolicy().hasHeightForWidth())
        self.authorityLineEdit.setSizePolicy(sizePolicy)
        self.authorityLineEdit.setMinimumSize(QtCore.QSize(278, 20))
        self.authorityLineEdit.setMaximumSize(QtCore.QSize(16777215, 20))
        self.authorityLineEdit.setStyleSheet("border-width:0.5px;\n"
"border-style: solid;\n"
"border-radius: 2px;\n"
"border-color:  rgb(100,100,100);\n"
"background-color: rgb(213, 234, 234);")
        self.authorityLineEdit.setInputMask("")
        self.authorityLineEdit.setReadOnly(True)
        self.authorityLineEdit.setObjectName("authorityLineEdit")
        self.gridLayout_19.addWidget(self.authorityLineEdit, 0, 1, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(6, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_19.addItem(spacerItem17, 0, 0, 1, 1)
        self.authorityStackedWidget.addWidget(self.authorityReadOnlyPage)
        self.authorityModifyPage = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.authorityModifyPage.sizePolicy().hasHeightForWidth())
        self.authorityModifyPage.setSizePolicy(sizePolicy)
        self.authorityModifyPage.setMinimumSize(QtCore.QSize(290, 20))
        self.authorityModifyPage.setObjectName("authorityModifyPage")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.authorityModifyPage)
        self.gridLayout_21.setContentsMargins(12, 0, 0, 0)
        self.gridLayout_21.setSpacing(0)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.authorityComboBox = QtWidgets.QComboBox(self.authorityModifyPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.authorityComboBox.sizePolicy().hasHeightForWidth())
        self.authorityComboBox.setSizePolicy(sizePolicy)
        self.authorityComboBox.setMinimumSize(QtCore.QSize(278, 20))
        self.authorityComboBox.setMaximumSize(QtCore.QSize(16777215, 20))
        self.authorityComboBox.setObjectName("authorityComboBox")
        self.gridLayout_21.addWidget(self.authorityComboBox, 0, 1, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(6, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_21.addItem(spacerItem18, 0, 0, 1, 1)
        self.authorityStackedWidget.addWidget(self.authorityModifyPage)
        self.horizontalLayout_10.addWidget(self.authorityStackedWidget)
        self.gridLayout_28.addLayout(self.horizontalLayout_10, 6, 0, 1, 1)
        self.gridLayout_12.addWidget(self.LsgRecordGroupBox, 0, 0, 2, 1)
        self.otherGroupBox = QtWidgets.QGroupBox(self.groupBox_3)
        self.otherGroupBox.setMinimumSize(QtCore.QSize(550, 85))
        self.otherGroupBox.setMaximumSize(QtCore.QSize(16777215, 85))
        self.otherGroupBox.setObjectName("otherGroupBox")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.otherGroupBox)
        self.gridLayout_23.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_23.setSpacing(6)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_13.setSpacing(6)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_2 = QtWidgets.QLabel(self.otherGroupBox)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_13.addWidget(self.label_2)
        self.stateStackedWidget = QtWidgets.QStackedWidget(self.otherGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stateStackedWidget.sizePolicy().hasHeightForWidth())
        self.stateStackedWidget.setSizePolicy(sizePolicy)
        self.stateStackedWidget.setMinimumSize(QtCore.QSize(200, 20))
        self.stateStackedWidget.setMaximumSize(QtCore.QSize(200, 20))
        self.stateStackedWidget.setObjectName("stateStackedWidget")
        self.stateReadOnlyPage = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stateReadOnlyPage.sizePolicy().hasHeightForWidth())
        self.stateReadOnlyPage.setSizePolicy(sizePolicy)
        self.stateReadOnlyPage.setMinimumSize(QtCore.QSize(200, 20))
        self.stateReadOnlyPage.setMaximumSize(QtCore.QSize(16777215, 20))
        self.stateReadOnlyPage.setObjectName("stateReadOnlyPage")
        self.stateLineEdit = QtWidgets.QLineEdit(self.stateReadOnlyPage)
        self.stateLineEdit.setGeometry(QtCore.QRect(0, 0, 200, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stateLineEdit.sizePolicy().hasHeightForWidth())
        self.stateLineEdit.setSizePolicy(sizePolicy)
        self.stateLineEdit.setMinimumSize(QtCore.QSize(200, 0))
        self.stateLineEdit.setMaximumSize(QtCore.QSize(16777215, 20))
        self.stateLineEdit.setStyleSheet("border-width:0.5px;\n"
"border-style: solid;\n"
"border-radius: 2px;\n"
"border-color:  rgb(100,100,100);\n"
"background-color: rgb(213, 234, 234);")
        self.stateLineEdit.setReadOnly(True)
        self.stateLineEdit.setObjectName("stateLineEdit")
        self.stateStackedWidget.addWidget(self.stateReadOnlyPage)
        self.stateModifyPage = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stateModifyPage.sizePolicy().hasHeightForWidth())
        self.stateModifyPage.setSizePolicy(sizePolicy)
        self.stateModifyPage.setObjectName("stateModifyPage")
        self.stateComboBox = QtWidgets.QComboBox(self.stateModifyPage)
        self.stateComboBox.setGeometry(QtCore.QRect(0, 0, 200, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stateComboBox.sizePolicy().hasHeightForWidth())
        self.stateComboBox.setSizePolicy(sizePolicy)
        self.stateComboBox.setMinimumSize(QtCore.QSize(200, 0))
        self.stateComboBox.setMaximumSize(QtCore.QSize(16777215, 41))
        self.stateComboBox.setObjectName("stateComboBox")
        self.stateStackedWidget.addWidget(self.stateModifyPage)
        self.horizontalLayout_13.addWidget(self.stateStackedWidget)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem19)
        self.label_3 = QtWidgets.QLabel(self.otherGroupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_13.addWidget(self.label_3)
        self.stateDateLineEdit = QtWidgets.QLineEdit(self.otherGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stateDateLineEdit.sizePolicy().hasHeightForWidth())
        self.stateDateLineEdit.setSizePolicy(sizePolicy)
        self.stateDateLineEdit.setMinimumSize(QtCore.QSize(0, 20))
        self.stateDateLineEdit.setMaximumSize(QtCore.QSize(80, 20))
        self.stateDateLineEdit.setStyleSheet("border-width:0.5px;\n"
"border-style: solid;\n"
"border-radius: 2px;\n"
"border-color:  rgb(100,100,100);\n"
"background-color: rgb(213, 234, 234);")
        self.stateDateLineEdit.setReadOnly(True)
        self.stateDateLineEdit.setObjectName("stateDateLineEdit")
        self.horizontalLayout_13.addWidget(self.stateDateLineEdit)
        self.gridLayout_23.addLayout(self.horizontalLayout_13, 0, 0, 1, 1)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setContentsMargins(11, 11, 10, 11)
        self.horizontalLayout_14.setSpacing(6)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.classLabel = QtWidgets.QLabel(self.otherGroupBox)
        self.classLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.classLabel.setObjectName("classLabel")
        self.horizontalLayout_14.addWidget(self.classLabel)
        self.classStackedWidget = QtWidgets.QStackedWidget(self.otherGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.classStackedWidget.sizePolicy().hasHeightForWidth())
        self.classStackedWidget.setSizePolicy(sizePolicy)
        self.classStackedWidget.setMinimumSize(QtCore.QSize(0, 20))
        self.classStackedWidget.setMaximumSize(QtCore.QSize(200, 20))
        self.classStackedWidget.setSizeIncrement(QtCore.QSize(0, 0))
        self.classStackedWidget.setObjectName("classStackedWidget")
        self.classReadOnlyPage = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.classReadOnlyPage.sizePolicy().hasHeightForWidth())
        self.classReadOnlyPage.setSizePolicy(sizePolicy)
        self.classReadOnlyPage.setMinimumSize(QtCore.QSize(200, 20))
        self.classReadOnlyPage.setMaximumSize(QtCore.QSize(200, 20))
        self.classReadOnlyPage.setObjectName("classReadOnlyPage")
        self.gridLayout_29 = QtWidgets.QGridLayout(self.classReadOnlyPage)
        self.gridLayout_29.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_29.setSpacing(0)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.classLineEdit = QtWidgets.QLineEdit(self.classReadOnlyPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.classLineEdit.sizePolicy().hasHeightForWidth())
        self.classLineEdit.setSizePolicy(sizePolicy)
        self.classLineEdit.setMinimumSize(QtCore.QSize(200, 20))
        self.classLineEdit.setMaximumSize(QtCore.QSize(16777215, 20))
        self.classLineEdit.setStyleSheet("border-width:0.5px;\n"
"border-style: solid;\n"
"border-radius: 2px;\n"
"border-color:  rgb(100,100,100);\n"
"background-color: rgb(213, 234, 234);")
        self.classLineEdit.setReadOnly(True)
        self.classLineEdit.setObjectName("classLineEdit")
        self.gridLayout_29.addWidget(self.classLineEdit, 0, 0, 1, 1)
        self.classStackedWidget.addWidget(self.classReadOnlyPage)
        self.classModifyPage = QtWidgets.QWidget()
        self.classModifyPage.setObjectName("classModifyPage")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.classModifyPage)
        self.gridLayout_22.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_22.setSpacing(0)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.classComboBox = QtWidgets.QComboBox(self.classModifyPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.classComboBox.sizePolicy().hasHeightForWidth())
        self.classComboBox.setSizePolicy(sizePolicy)
        self.classComboBox.setMinimumSize(QtCore.QSize(0, 20))
        self.classComboBox.setMaximumSize(QtCore.QSize(200, 20))
        self.classComboBox.setObjectName("classComboBox")
        self.gridLayout_22.addWidget(self.classComboBox, 0, 0, 1, 1)
        self.classStackedWidget.addWidget(self.classModifyPage)
        self.horizontalLayout_14.addWidget(self.classStackedWidget)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem20)
        self.gridLayout_23.addLayout(self.horizontalLayout_14, 1, 0, 1, 1)
        self.gridLayout_12.addWidget(self.otherGroupBox, 3, 0, 1, 1)
        self.linkEsuGroupBox = QtWidgets.QGroupBox(self.groupBox_3)
        self.linkEsuGroupBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.linkEsuGroupBox.setObjectName("linkEsuGroupBox")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.linkEsuGroupBox)
        self.gridLayout_20.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_20.setSpacing(6)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.linkEsuListWidget = QtWidgets.QListWidget(self.linkEsuGroupBox)
        self.linkEsuListWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.linkEsuListWidget.setStyleSheet("border-width:0.5px;\n"
"border-style: solid;\n"
"border-radius: 2px;\n"
"border-color:  rgb(100,100,100);\n"
"background-color: rgb(213, 234, 234);")
        self.linkEsuListWidget.setObjectName("linkEsuListWidget")
        self.gridLayout_20.addWidget(self.linkEsuListWidget, 0, 0, 1, 1)
        self.editEsuPushButton = QtWidgets.QPushButton(self.linkEsuGroupBox)
        self.editEsuPushButton.setEnabled(False)
        self.editEsuPushButton.setMinimumSize(QtCore.QSize(0, 33))
        self.editEsuPushButton.setMaximumSize(QtCore.QSize(153, 23))
        self.editEsuPushButton.setObjectName("editEsuPushButton")
        self.gridLayout_20.addWidget(self.editEsuPushButton, 0, 1, 1, 1)
        self.gridLayout_12.addWidget(self.linkEsuGroupBox, 2, 1, 2, 1)
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox.setMinimumSize(QtCore.QSize(421, 115))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 125))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_24.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_24.setSpacing(6)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_15.setSpacing(6)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.endYLabel = QtWidgets.QLabel(self.groupBox)
        self.endYLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.endYLabel.setAutoFillBackground(False)
        self.endYLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.endYLabel.setObjectName("endYLabel")
        self.gridLayout_15.addWidget(self.endYLabel, 1, 2, 1, 1)
        self.endXLineEdit = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.endXLineEdit.sizePolicy().hasHeightForWidth())
        self.endXLineEdit.setSizePolicy(sizePolicy)
        self.endXLineEdit.setMinimumSize(QtCore.QSize(106, 20))
        self.endXLineEdit.setMaximumSize(QtCore.QSize(16777215, 20))
        self.endXLineEdit.setStyleSheet("border-width:0.5px;\n"
"border-style: solid;\n"
"border-radius: 2px;\n"
"border-color:  rgb(100,100,100);\n"
"background-color: rgb(213, 234, 234);")
        self.endXLineEdit.setReadOnly(True)
        self.endXLineEdit.setObjectName("endXLineEdit")
        self.gridLayout_15.addWidget(self.endXLineEdit, 1, 1, 1, 1)
        self.endXLabel = QtWidgets.QLabel(self.groupBox)
        self.endXLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.endXLabel.setObjectName("endXLabel")
        self.gridLayout_15.addWidget(self.endXLabel, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem21)
        self.tolLabel = QtWidgets.QLabel(self.groupBox)
        self.tolLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tolLabel.setObjectName("tolLabel")
        self.horizontalLayout_3.addWidget(self.tolLabel)
        self.tolLineEdit = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tolLineEdit.sizePolicy().hasHeightForWidth())
        self.tolLineEdit.setSizePolicy(sizePolicy)
        self.tolLineEdit.setMinimumSize(QtCore.QSize(50, 0))
        self.tolLineEdit.setMaximumSize(QtCore.QSize(50, 20))
        self.tolLineEdit.setStyleSheet("border-width:0.5px;\n"
"border-style: solid;\n"
"border-radius: 2px;\n"
"border-color:  rgb(100,100,100);\n"
"background-color: rgb(213, 234, 234);")
        self.tolLineEdit.setReadOnly(True)
        self.tolLineEdit.setObjectName("tolLineEdit")
        self.horizontalLayout_3.addWidget(self.tolLineEdit)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.gridLayout_15.addLayout(self.horizontalLayout_3, 0, 4, 1, 1)
        self.startYLabel = QtWidgets.QLabel(self.groupBox)
        self.startYLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.startYLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.startYLabel.setObjectName("startYLabel")
        self.gridLayout_15.addWidget(self.startYLabel, 0, 2, 1, 1)
        self.startYLineEdit = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startYLineEdit.sizePolicy().hasHeightForWidth())
        self.startYLineEdit.setSizePolicy(sizePolicy)
        self.startYLineEdit.setMinimumSize(QtCore.QSize(84, 20))
        self.startYLineEdit.setMaximumSize(QtCore.QSize(16777215, 20))
        self.startYLineEdit.setStyleSheet("border-width:0.5px;\n"
"border-style: solid;\n"
"border-radius: 2px;\n"
"border-color:  rgb(100,100,100);\n"
"background-color: rgb(213, 234, 234);")
        self.startYLineEdit.setReadOnly(True)
        self.startYLineEdit.setObjectName("startYLineEdit")
        self.gridLayout_15.addWidget(self.startYLineEdit, 0, 3, 1, 1)
        self.startXLineEdit = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startXLineEdit.sizePolicy().hasHeightForWidth())
        self.startXLineEdit.setSizePolicy(sizePolicy)
        self.startXLineEdit.setMinimumSize(QtCore.QSize(84, 20))
        self.startXLineEdit.setMaximumSize(QtCore.QSize(16777215, 20))
        self.startXLineEdit.setStyleSheet("border-width:0.5px;\n"
"border-style: solid;\n"
"border-radius: 2px;\n"
"border-color:  rgb(100,100,100);\n"
"background-color: rgb(213, 234, 234);")
        self.startXLineEdit.setReadOnly(True)
        self.startXLineEdit.setObjectName("startXLineEdit")
        self.gridLayout_15.addWidget(self.startXLineEdit, 0, 1, 1, 1)
        self.startXLabel = QtWidgets.QLabel(self.groupBox)
        self.startXLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.startXLabel.setObjectName("startXLabel")
        self.gridLayout_15.addWidget(self.startXLabel, 0, 0, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_11.setSpacing(6)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem22 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem22)
        self.showPushButton = QtWidgets.QPushButton(self.groupBox)
        self.showPushButton.setMaximumSize(QtCore.QSize(60, 25))
        self.showPushButton.setObjectName("showPushButton")
        self.horizontalLayout_11.addWidget(self.showPushButton)
        spacerItem23 = QtWidgets.QSpacerItem(4, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem23)
        self.gridLayout_15.addLayout(self.horizontalLayout_11, 1, 4, 1, 1)
        self.endYLineEdit = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.endYLineEdit.sizePolicy().hasHeightForWidth())
        self.endYLineEdit.setSizePolicy(sizePolicy)
        self.endYLineEdit.setMinimumSize(QtCore.QSize(106, 20))
        self.endYLineEdit.setMaximumSize(QtCore.QSize(16777215, 20))
        self.endYLineEdit.setStyleSheet("border-width:0.5px;\n"
"border-style: solid;\n"
"border-radius: 2px;\n"
"border-color:  rgb(100,100,100);\n"
"background-color: rgb(213, 234, 234);")
        self.endYLineEdit.setReadOnly(True)
        self.endYLineEdit.setObjectName("endYLineEdit")
        self.gridLayout_15.addWidget(self.endYLineEdit, 1, 3, 1, 1)
        self.gridLayout_24.addLayout(self.gridLayout_15, 0, 0, 1, 1)
        self.editCoordsPushButton = QtWidgets.QPushButton(self.groupBox)
        self.editCoordsPushButton.setEnabled(False)
        self.editCoordsPushButton.setMinimumSize(QtCore.QSize(0, 23))
        self.editCoordsPushButton.setMaximumSize(QtCore.QSize(153, 23))
        self.editCoordsPushButton.setObjectName("editCoordsPushButton")
        self.gridLayout_24.addWidget(self.editCoordsPushButton, 1, 0, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox, 2, 0, 1, 1)
        self.navigationGroupBox = QtWidgets.QGroupBox(self.groupBox_3)
        self.navigationGroupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.navigationGroupBox.setMaximumSize(QtCore.QSize(16777215, 85))
        self.navigationGroupBox.setObjectName("navigationGroupBox")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.navigationGroupBox)
        self.gridLayout_7.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_7.setSpacing(6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.firstPushButton = QtWidgets.QPushButton(self.navigationGroupBox)
        self.firstPushButton.setMinimumSize(QtCore.QSize(0, 0))
        self.firstPushButton.setMaximumSize(QtCore.QSize(120, 16777215))
        self.firstPushButton.setObjectName("firstPushButton")
        self.gridLayout_7.addWidget(self.firstPushButton, 0, 0, 1, 1)
        self.previousPushButton = QtWidgets.QPushButton(self.navigationGroupBox)
        self.previousPushButton.setMaximumSize(QtCore.QSize(120, 16777215))
        self.previousPushButton.setObjectName("previousPushButton")
        self.gridLayout_7.addWidget(self.previousPushButton, 0, 1, 1, 1)
        self.nextPushButton = QtWidgets.QPushButton(self.navigationGroupBox)
        self.nextPushButton.setMaximumSize(QtCore.QSize(120, 16777215))
        self.nextPushButton.setObjectName("nextPushButton")
        self.gridLayout_7.addWidget(self.nextPushButton, 0, 2, 1, 1)
        self.lastPushButton = QtWidgets.QPushButton(self.navigationGroupBox)
        self.lastPushButton.setMaximumSize(QtCore.QSize(120, 16777215))
        self.lastPushButton.setObjectName("lastPushButton")
        self.gridLayout_7.addWidget(self.lastPushButton, 0, 3, 1, 1)
        self.gridLayout_12.addWidget(self.navigationGroupBox, 5, 0, 1, 1)
        self.crossReferenceGroupBox = QtWidgets.QGroupBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.crossReferenceGroupBox.sizePolicy().hasHeightForWidth())
        self.crossReferenceGroupBox.setSizePolicy(sizePolicy)
        self.crossReferenceGroupBox.setMinimumSize(QtCore.QSize(378, 230))
        self.crossReferenceGroupBox.setMaximumSize(QtCore.QSize(16777215, 250))
        self.crossReferenceGroupBox.setBaseSize(QtCore.QSize(0, 25))
        self.crossReferenceGroupBox.setObjectName("crossReferenceGroupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.crossReferenceGroupBox)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.crossReferenceTableView = QtWidgets.QTableView(self.crossReferenceGroupBox)
        self.crossReferenceTableView.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.crossReferenceTableView.setFont(font)
        self.crossReferenceTableView.setStyleSheet("border-width:0.5px;\n"
"border-style: solid;\n"
"border-radius: 2px;\n"
"border-color:  rgb(100,100,100);\n"
"background-color: rgb(213, 234, 234);")
        self.crossReferenceTableView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.crossReferenceTableView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.crossReferenceTableView.setEditTriggers(QtWidgets.QAbstractItemView.AllEditTriggers)
        self.crossReferenceTableView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.crossReferenceTableView.setGridStyle(QtCore.Qt.NoPen)
        self.crossReferenceTableView.setObjectName("crossReferenceTableView")
        self.crossReferenceTableView.horizontalHeader().setVisible(False)
        self.crossReferenceTableView.horizontalHeader().setStretchLastSection(True)
        self.crossReferenceTableView.verticalHeader().setVisible(False)
        self.gridLayout_2.addWidget(self.crossReferenceTableView, 1, 0, 1, 1)
        self.viewPushButton = QtWidgets.QPushButton(self.crossReferenceGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewPushButton.sizePolicy().hasHeightForWidth())
        self.viewPushButton.setSizePolicy(sizePolicy)
        self.viewPushButton.setMinimumSize(QtCore.QSize(75, 0))
        self.viewPushButton.setMaximumSize(QtCore.QSize(60, 16777215))
        self.viewPushButton.setObjectName("viewPushButton")
        self.gridLayout_2.addWidget(self.viewPushButton, 1, 1, 1, 1)
        self.gridLayout_12.addWidget(self.crossReferenceGroupBox, 1, 1, 1, 1)
        spacerItem24 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem24, 4, 0, 1, 1)
        self.operationsGroupBox.raise_()
        self.crossReferenceGroupBox.raise_()
        self.groupBox.raise_()
        self.otherGroupBox.raise_()
        self.LsgRecordGroupBox.raise_()
        self.navigationGroupBox.raise_()
        self.linkEsuGroupBox.raise_()
        self.gridLayout_34.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_32.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(streetBrowserDialog)
        self.srwrTabWidget.setCurrentIndex(0)
        self.localityStackedWidget.setCurrentIndex(0)
        self.townStackedWidget.setCurrentIndex(0)
        self.typeStackedWidget.setCurrentIndex(0)
        self.startDateStackedWidget.setCurrentIndex(0)
        self.countyStackedWidget.setCurrentIndex(0)
        self.authorityStackedWidget.setCurrentIndex(0)
        self.stateStackedWidget.setCurrentIndex(0)
        self.classStackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(streetBrowserDialog)

    def retranslateUi(self, streetBrowserDialog):
        _translate = QtCore.QCoreApplication.translate
        streetBrowserDialog.setWindowTitle(_translate("streetBrowserDialog", "roadNet - Street Browser"))
        self.srwrRecordsGroupBox.setTitle(_translate("streetBrowserDialog", "SRWR Records"))
        self.srwrTabWidget.setTabText(self.srwrTabWidget.indexOf(self.maintenanceTab), _translate("streetBrowserDialog", "Maintenance"))
        self.srwrTabWidget.setTabText(self.srwrTabWidget.indexOf(self.specialDesignationsTab), _translate("streetBrowserDialog", "Special Designations"))
        self.srwrTabWidget.setTabText(self.srwrTabWidget.indexOf(self.reinstatementCatsTab), _translate("streetBrowserDialog", "Reinstatement Categories"))
        self.groupBox_2.setTitle(_translate("streetBrowserDialog", "Maintenance Operations"))
        self.srwrAddPushButton.setText(_translate("streetBrowserDialog", "Add"))
        self.srwrModifyPushButton.setText(_translate("streetBrowserDialog", "Modify"))
        self.srwrDeletePushButton.setText(_translate("streetBrowserDialog", "Delete"))
        self.srwrViewPushButton.setText(_translate("streetBrowserDialog", "View"))
        self.srwrExtentPushButton.setText(_translate("streetBrowserDialog", "Show Extents"))
        self.groupBox_3.setTitle(_translate("streetBrowserDialog", "LSG Record"))
        self.srwrPushButton.setText(_translate("streetBrowserDialog", "Show SRWR Details"))
        self.operationsGroupBox.setTitle(_translate("streetBrowserDialog", "LSG Operations"))
        self.addPushButton.setText(_translate("streetBrowserDialog", "Add"))
        self.modifyPushButton.setText(_translate("streetBrowserDialog", "Modify"))
        self.closeOpPushButton.setText(_translate("streetBrowserDialog", "Delete"))
        self.filterPushButton.setText(_translate("streetBrowserDialog", "Filter"))
        self.mapPushButton.setText(_translate("streetBrowserDialog", "Map"))
        self.LsgRecordGroupBox.setTitle(_translate("streetBrowserDialog", "Record"))
        self.descriptionLabel.setText(_translate("streetBrowserDialog", "Description"))
        self.localityLabel.setText(_translate("streetBrowserDialog", "Locality"))
        self.townLabel.setText(_translate("streetBrowserDialog", "Town"))
        self.typeLabel.setText(_translate("streetBrowserDialog", "Type"))
        self.startDateLabel.setText(_translate("streetBrowserDialog", "Start Date"))
        self.entryDateLabel.setText(_translate("streetBrowserDialog", "Entry Date"))
        self.lastUpdateLabel.setText(_translate("streetBrowserDialog", "Last Update"))
        self.byLabel.setText(_translate("streetBrowserDialog", "By"))
        self.countyLabel.setText(_translate("streetBrowserDialog", "County"))
        self.usrnLabel_2.setText(_translate("streetBrowserDialog", "USRN"))
        self.versionLabel.setText(_translate("streetBrowserDialog", "Version"))
        self.authorityLabel.setText(_translate("streetBrowserDialog", "Authority"))
        self.otherGroupBox.setTitle(_translate("streetBrowserDialog", "Other"))
        self.label_2.setText(_translate("streetBrowserDialog", "State"))
        self.label_3.setText(_translate("streetBrowserDialog", "Date:"))
        self.classLabel.setText(_translate("streetBrowserDialog", "Class"))
        self.linkEsuGroupBox.setTitle(_translate("streetBrowserDialog", "ESUs"))
        self.editEsuPushButton.setText(_translate("streetBrowserDialog", "Edit ESU\n"
"Links"))
        self.groupBox.setTitle(_translate("streetBrowserDialog", "Coordinates"))
        self.endYLabel.setText(_translate("streetBrowserDialog", "End Y"))
        self.endXLabel.setText(_translate("streetBrowserDialog", "End X"))
        self.tolLabel.setText(_translate("streetBrowserDialog", "Tol"))
        self.label.setText(_translate("streetBrowserDialog", "m"))
        self.startYLabel.setText(_translate("streetBrowserDialog", "Start Y"))
        self.startXLabel.setText(_translate("streetBrowserDialog", "Start X"))
        self.showPushButton.setText(_translate("streetBrowserDialog", "Show"))
        self.editCoordsPushButton.setText(_translate("streetBrowserDialog", "Edit Start/End Coordinates"))
        self.navigationGroupBox.setTitle(_translate("streetBrowserDialog", "Navigation"))
        self.firstPushButton.setText(_translate("streetBrowserDialog", "First"))
        self.previousPushButton.setText(_translate("streetBrowserDialog", "Previous"))
        self.nextPushButton.setText(_translate("streetBrowserDialog", "Next"))
        self.lastPushButton.setText(_translate("streetBrowserDialog", "Last"))
        self.crossReferenceGroupBox.setTitle(_translate("streetBrowserDialog", "Cross Reference"))
        self.viewPushButton.setText(_translate("streetBrowserDialog", "View"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    streetBrowserDialog = QtWidgets.QDialog()
    ui = Ui_streetBrowserDialog()
    ui.setupUi(streetBrowserDialog)
    streetBrowserDialog.show()
    sys.exit(app.exec_())

