# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ramp_mcl_editor_ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MclEditorDialog(object):
    def setupUi(self, MclEditorDialog):
        MclEditorDialog.setObjectName("MclEditorDialog")
        MclEditorDialog.resize(694, 473)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MclEditorDialog.sizePolicy().hasHeightForWidth())
        MclEditorDialog.setSizePolicy(sizePolicy)
        MclEditorDialog.setMinimumSize(QtCore.QSize(562, 473))
        MclEditorDialog.setMaximumSize(QtCore.QSize(694, 473))
        self.buttonBox = QtWidgets.QDialogButtonBox(MclEditorDialog)
        self.buttonBox.setGeometry(QtCore.QRect(480, 440, 211, 27))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.groupBox_2 = QtWidgets.QGroupBox(MclEditorDialog)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 362, 80))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 2, 1, 1)
        self.mclLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.mclLineEdit.setAutoFillBackground(False)
        self.mclLineEdit.setStyleSheet("border-width:0.5px;\n"
"border-style: solid;\n"
"border-radius: 2px;\n"
"border-color:  rgb(100,100,100);\n"
"background-color: rgb(213, 234, 234);")
        self.mclLineEdit.setReadOnly(True)
        self.mclLineEdit.setObjectName("mclLineEdit")
        self.gridLayout_2.addWidget(self.mclLineEdit, 1, 0, 1, 1)
        self.combinedRefLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.combinedRefLineEdit.setStyleSheet("border-width:0.5px;\n"
"border-style: solid;\n"
"border-radius: 2px;\n"
"border-color:  rgb(100,100,100);\n"
"background-color: rgb(213, 234, 234);")
        self.combinedRefLineEdit.setReadOnly(True)
        self.combinedRefLineEdit.setObjectName("combinedRefLineEdit")
        self.gridLayout_2.addWidget(self.combinedRefLineEdit, 1, 1, 1, 1)
        self.lengthLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.lengthLineEdit.setStyleSheet("border-width:0.5px;\n"
"border-style: solid;\n"
"border-radius: 2px;\n"
"border-color:  rgb(100,100,100);\n"
"background-color: rgb(213, 234, 234);")
        self.lengthLineEdit.setReadOnly(True)
        self.lengthLineEdit.setObjectName("lengthLineEdit")
        self.gridLayout_2.addWidget(self.lengthLineEdit, 1, 2, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(MclEditorDialog)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 100, 551, 321))
        self.groupBox_3.setObjectName("groupBox_3")
        self.widget = QtWidgets.QWidget(self.groupBox_3)
        self.widget.setGeometry(QtCore.QRect(19, 27, 271, 170))
        self.widget.setObjectName("widget")
        self.formLayout_3 = QtWidgets.QFormLayout(self.widget)
        self.formLayout_3.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.usrnLineEdit = QtWidgets.QLineEdit(self.widget)
        self.usrnLineEdit.setObjectName("usrnLineEdit")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.usrnLineEdit)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.ref1LineEdit = QtWidgets.QLineEdit(self.widget)
        self.ref1LineEdit.setObjectName("ref1LineEdit")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ref1LineEdit)
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setObjectName("label_8")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.ref2LineEdit = QtWidgets.QLineEdit(self.widget)
        self.ref2LineEdit.setObjectName("ref2LineEdit")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.ref2LineEdit)
        self.streetClassComboBox = QtWidgets.QComboBox(self.widget)
        self.streetClassComboBox.setObjectName("streetClassComboBox")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.streetClassComboBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_3.setItem(4, QtWidgets.QFormLayout.FieldRole, spacerItem)
        self.sectionDescriptionPlainTextEdit = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.sectionDescriptionPlainTextEdit.setGeometry(QtCore.QRect(19, 240, 521, 78))
        self.sectionDescriptionPlainTextEdit.setObjectName("sectionDescriptionPlainTextEdit")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(19, 210, 119, 19))
        self.label_3.setObjectName("label_3")
        self.widget1 = QtWidgets.QWidget(self.groupBox_3)
        self.widget1.setGeometry(QtCore.QRect(299, 27, 241, 201))
        self.widget1.setObjectName("widget1")
        self.formLayout_2 = QtWidgets.QFormLayout(self.widget1)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_13 = QtWidgets.QLabel(self.widget1)
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.label_10 = QtWidgets.QLabel(self.widget1)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.label_11 = QtWidgets.QLabel(self.widget1)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.label_12 = QtWidgets.QLabel(self.widget1)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.label_14 = QtWidgets.QLabel(self.widget1)
        self.label_14.setObjectName("label_14")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.laneNumberComboBox = QtWidgets.QComboBox(self.widget1)
        self.laneNumberComboBox.setObjectName("laneNumberComboBox")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.laneNumberComboBox)
        self.carriagewayComboBox = QtWidgets.QComboBox(self.widget1)
        self.carriagewayComboBox.setObjectName("carriagewayComboBox")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.carriagewayComboBox)
        self.ruralUrbanComboBox = QtWidgets.QComboBox(self.widget1)
        self.ruralUrbanComboBox.setObjectName("ruralUrbanComboBox")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ruralUrbanComboBox)
        self.speedLimitComboBox = QtWidgets.QComboBox(self.widget1)
        self.speedLimitComboBox.setObjectName("speedLimitComboBox")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.speedLimitComboBox)
        self.sectionTypeComboBox = QtWidgets.QComboBox(self.widget1)
        self.sectionTypeComboBox.setObjectName("sectionTypeComboBox")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.sectionTypeComboBox)
        self.groupBox = QtWidgets.QGroupBox(MclEditorDialog)
        self.groupBox.setGeometry(QtCore.QRect(570, 100, 111, 261))
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.editLinksPushButton = QtWidgets.QPushButton(self.groupBox)
        self.editLinksPushButton.setObjectName("editLinksPushButton")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.editLinksPushButton)
        self.linkedPolygonsListWidget = QtWidgets.QListWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.linkedPolygonsListWidget.sizePolicy().hasHeightForWidth())
        self.linkedPolygonsListWidget.setSizePolicy(sizePolicy)
        self.linkedPolygonsListWidget.setMinimumSize(QtCore.QSize(85, 192))
        self.linkedPolygonsListWidget.setMaximumSize(QtCore.QSize(85, 192))
        self.linkedPolygonsListWidget.setStyleSheet("border-width:0.5px;\n"
"border-style: solid;\n"
"border-radius: 2px;\n"
"border-color:  rgb(100,100,100);\n"
"background-color: rgb(213, 234, 234);")
        self.linkedPolygonsListWidget.setObjectName("linkedPolygonsListWidget")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.linkedPolygonsListWidget)
        self.groupBox_2.raise_()
        self.groupBox_3.raise_()
        self.groupBox.raise_()
        self.buttonBox.raise_()

        self.retranslateUi(MclEditorDialog)
        self.buttonBox.accepted.connect(MclEditorDialog.accept)
        self.buttonBox.rejected.connect(MclEditorDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(MclEditorDialog)
        MclEditorDialog.setTabOrder(self.usrnLineEdit, self.streetClassComboBox)
        MclEditorDialog.setTabOrder(self.streetClassComboBox, self.ref1LineEdit)
        MclEditorDialog.setTabOrder(self.ref1LineEdit, self.ref2LineEdit)
        MclEditorDialog.setTabOrder(self.ref2LineEdit, self.laneNumberComboBox)
        MclEditorDialog.setTabOrder(self.laneNumberComboBox, self.carriagewayComboBox)
        MclEditorDialog.setTabOrder(self.carriagewayComboBox, self.ruralUrbanComboBox)
        MclEditorDialog.setTabOrder(self.ruralUrbanComboBox, self.speedLimitComboBox)
        MclEditorDialog.setTabOrder(self.speedLimitComboBox, self.sectionTypeComboBox)
        MclEditorDialog.setTabOrder(self.sectionTypeComboBox, self.sectionDescriptionPlainTextEdit)
        MclEditorDialog.setTabOrder(self.sectionDescriptionPlainTextEdit, self.editLinksPushButton)
        MclEditorDialog.setTabOrder(self.editLinksPushButton, self.linkedPolygonsListWidget)
        MclEditorDialog.setTabOrder(self.linkedPolygonsListWidget, self.mclLineEdit)
        MclEditorDialog.setTabOrder(self.mclLineEdit, self.combinedRefLineEdit)
        MclEditorDialog.setTabOrder(self.combinedRefLineEdit, self.lengthLineEdit)
        MclEditorDialog.setTabOrder(self.lengthLineEdit, self.buttonBox)

    def retranslateUi(self, MclEditorDialog):
        _translate = QtCore.QCoreApplication.translate
        MclEditorDialog.setWindowTitle(_translate("MclEditorDialog", "RAMP - Edit MCL"))
        self.groupBox_2.setTitle(_translate("MclEditorDialog", "Fixed Attributes"))
        self.label.setText(_translate("MclEditorDialog", "MCL ID:"))
        self.label_4.setText(_translate("MclEditorDialog", "Combined Ref:"))
        self.label_7.setText(_translate("MclEditorDialog", "Length (m):"))
        self.groupBox_3.setTitle(_translate("MclEditorDialog", "Editable Attributes"))
        self.label_2.setText(_translate("MclEditorDialog", "USRN:"))
        self.label_5.setText(_translate("MclEditorDialog", "Street Class:"))
        self.label_6.setText(_translate("MclEditorDialog", "Ref 1:"))
        self.label_8.setText(_translate("MclEditorDialog", "Ref 2:"))
        self.label_3.setText(_translate("MclEditorDialog", "Section Desciption:"))
        self.label_13.setText(_translate("MclEditorDialog", "Carriageway:"))
        self.label_10.setText(_translate("MclEditorDialog", "Rural / Urban:"))
        self.label_11.setText(_translate("MclEditorDialog", "Speed Limit:"))
        self.label_12.setText(_translate("MclEditorDialog", "Section Type:"))
        self.label_14.setText(_translate("MclEditorDialog", "Number of Lanes:"))
        self.groupBox.setTitle(_translate("MclEditorDialog", "Linked Polygons"))
        self.editLinksPushButton.setText(_translate("MclEditorDialog", "Edit Links"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MclEditorDialog = QtWidgets.QDialog()
    ui = Ui_MclEditorDialog()
    ui.setupUi(MclEditorDialog)
    MclEditorDialog.show()
    sys.exit(app.exec_())

